const pokes = [
  { id: 1, name: 'フシギダネ', keyword: ['フシギダネ'], image: '/pokemon-ierukana/assets/images/001Bulbasaur.png' },
  { id: 2, name: 'フシギソウ', keyword: ['フシギソウ'], image: '/pokemon-ierukana/assets/images/002Ivysaur.png' },
  { id: 3, name: 'フシギバナ', keyword: ['フシギバナ'], image: '/pokemon-ierukana/assets/images/003Venusaur.png' },
  { id: 4, name: 'ヒトカゲ', keyword: ['ヒトカゲ'], image: '/pokemon-ierukana/assets/images/004Charmander.png' },
  { id: 5, name: 'リザード', keyword: ['リザード'], image: '/pokemon-ierukana/assets/images/005Charmeleon.png' },
  { id: 6, name: 'リザードン', keyword: ['リザードン'], image: '/pokemon-ierukana/assets/images/006Charizard.png' },
  { id: 7, name: 'ゼニガメ', keyword: ['ゼニガメ'], image: '/pokemon-ierukana/assets/images/007Squirtle.png' },
  { id: 8, name: 'カメール', keyword: ['カメール'], image: '/pokemon-ierukana/assets/images/008Wartortle.png' },
  { id: 9, name: 'カメックス', keyword: ['カメックス'], image: '/pokemon-ierukana/assets/images/009Blastoise.png' },
  { id: 10, name: 'キャタピー', keyword: ['キャタピー'], image: '/pokemon-ierukana/assets/images/010Caterpie.png' },
  { id: 11, name: 'トランセル', keyword: ['トランセル'], image: '/pokemon-ierukana/assets/images/011Metapod.png' },
  { id: 12, name: 'バタフリー', keyword: ['バタフリー'], image: '/pokemon-ierukana/assets/images/012Butterfree.png' },
  { id: 13, name: 'ビードル', keyword: ['ビードル'], image: '/pokemon-ierukana/assets/images/013Weedle.png' },
  { id: 14, name: 'コクーン', keyword: ['コクーン'], image: '/pokemon-ierukana/assets/images/014Kakuna.png' },
  { id: 15, name: 'スピアー', keyword: ['スピアー'], image: '/pokemon-ierukana/assets/images/015Beedrill.png' },
  { id: 16, name: 'ポッポ', keyword: ['ポッポ'], image: '/pokemon-ierukana/assets/images/016Pidgey.png' },
  { id: 17, name: 'ピジョン', keyword: ['ピジョン'], image: '/pokemon-ierukana/assets/images/017Pidgeotto.png' },
  { id: 18, name: 'ピジョット', keyword: ['ピジョット'], image: '/pokemon-ierukana/assets/images/018Pidgeot.png' },
  { id: 19, name: 'コラッタ', keyword: ['コラッタ'], image: '/pokemon-ierukana/assets/images/019Rattata.png' },
  { id: 20, name: 'ラッタ', keyword: ['ラッタ'], image: '/pokemon-ierukana/assets/images/020Raticate.png' },
  { id: 21, name: 'オニスズメ', keyword: ['オニスズメ'], image: '/pokemon-ierukana/assets/images/021Spearow.png' },
  { id: 22, name: 'オニドリル', keyword: ['オニドリル'], image: '/pokemon-ierukana/assets/images/022Fearow.png' },
  { id: 23, name: 'アーボ', keyword: ['アーボ'], image: '/pokemon-ierukana/assets/images/023Ekans.png' },
  { id: 24, name: 'アーボック', keyword: ['アーボック'], image: '/pokemon-ierukana/assets/images/024Arbok.png' },
  { id: 25, name: 'ピカチュウ', keyword: ['ピカチュウ'], image: '/pokemon-ierukana/assets/images/025Pikachu.png' },
  { id: 26, name: 'ライチュウ', keyword: ['ライチュウ'], image: '/pokemon-ierukana/assets/images/026Raichu.png' },
  { id: 27, name: 'サンド', keyword: ['サンド'], image: '/pokemon-ierukana/assets/images/027Sandshrew.png' },
  { id: 28, name: 'サンドパン', keyword: ['サンドパン'], image: '/pokemon-ierukana/assets/images/028Sandslash.png' },
  { id: 29, name: 'ニドラン♀', keyword: ['ニドラン♀', 'ニドランメス'], image: '/pokemon-ierukana/assets/images/029Nidoran.png' },
  { id: 30, name: 'ニドリーナ', keyword: ['ニドリーナ'], image: '/pokemon-ierukana/assets/images/030Nidorina.png' },
  { id: 31, name: 'ニドクイン', keyword: ['ニドクイン'], image: '/pokemon-ierukana/assets/images/031Nidoqueen.png' },
  { id: 32, name: 'ニドラン♂', keyword: ['ニドラン♂', 'ニドランオス'], image: '/pokemon-ierukana/assets/images/032Nidoran.png' },
  { id: 33, name: 'ニドリーノ', keyword: ['ニドリーノ'], image: '/pokemon-ierukana/assets/images/033Nidorino.png' },
  { id: 34, name: 'ニドキング', keyword: ['ニドキング'], image: '/pokemon-ierukana/assets/images/034Nidoking.png' },
  { id: 35, name: 'ピッピ', keyword: ['ピッピ'], image: '/pokemon-ierukana/assets/images/035Clefairy.png' },
  { id: 36, name: 'ピクシー', keyword: ['ピクシー'], image: '/pokemon-ierukana/assets/images/036Clefable.png' },
  { id: 37, name: 'ロコン', keyword: ['ロコン'], image: '/pokemon-ierukana/assets/images/037Vulpix.png' },
  { id: 38, name: 'キュウコン', keyword: ['キュウコン'], image: '/pokemon-ierukana/assets/images/038Ninetales.png' },
  { id: 39, name: 'プリン', keyword: ['プリン'], image: '/pokemon-ierukana/assets/images/039Jigglypuff.png' },
  { id: 40, name: 'プクリン', keyword: ['プクリン'], image: '/pokemon-ierukana/assets/images/040Wigglytuff.png' },
  { id: 41, name: 'ズバット', keyword: ['ズバット'], image: '/pokemon-ierukana/assets/images/041Zubat.png' },
  { id: 42, name: 'ゴルバット', keyword: ['ゴルバット'], image: '/pokemon-ierukana/assets/images/042Golbat.png' },
  { id: 43, name: 'ナゾノクサ', keyword: ['ナゾノクサ'], image: '/pokemon-ierukana/assets/images/043Oddish.png' },
  { id: 44, name: 'クサイハナ', keyword: ['クサイハナ'], image: '/pokemon-ierukana/assets/images/044Gloom.png' },
  { id: 45, name: 'ラフレシア', keyword: ['ラフレシア'], image: '/pokemon-ierukana/assets/images/045Vileplume.png' },
  { id: 46, name: 'パラス', keyword: ['パラス'], image: '/pokemon-ierukana/assets/images/046Paras.png' },
  { id: 47, name: 'パラセクト', keyword: ['パラセクト'], image: '/pokemon-ierukana/assets/images/047Parasect.png' },
  { id: 48, name: 'コンパン', keyword: ['コンパン'], image: '/pokemon-ierukana/assets/images/048Venonat.png' },
  { id: 49, name: 'モルフォン', keyword: ['モルフォン'], image: '/pokemon-ierukana/assets/images/049Venomoth.png' },
  { id: 50, name: 'ディグダ', keyword: ['ディグダ'], image: '/pokemon-ierukana/assets/images/050Diglett.png' },
  { id: 51, name: 'ダグトリオ', keyword: ['ダグトリオ'], image: '/pokemon-ierukana/assets/images/051Dugtrio.png' },
  { id: 52, name: 'ニャース', keyword: ['ニャース'], image: '/pokemon-ierukana/assets/images/052Meowth.png' },
  { id: 53, name: 'ペルシアン', keyword: ['ペルシアン'], image: '/pokemon-ierukana/assets/images/053Persian.png' },
  { id: 54, name: 'コダック', keyword: ['コダック'], image: '/pokemon-ierukana/assets/images/054Psyduck.png' },
  { id: 55, name: 'ゴルダック', keyword: ['ゴルダック'], image: '/pokemon-ierukana/assets/images/055Golduck.png' },
  { id: 56, name: 'マンキー', keyword: ['マンキー'], image: '/pokemon-ierukana/assets/images/056Mankey.png' },
  { id: 57, name: 'オコリザル', keyword: ['オコリザル'], image: '/pokemon-ierukana/assets/images/057Primeape.png' },
  { id: 58, name: 'ガーディ', keyword: ['ガーディ'], image: '/pokemon-ierukana/assets/images/058Growlithe.png' },
  { id: 59, name: 'ウインディ', keyword: ['ウインディ'], image: '/pokemon-ierukana/assets/images/059Arcanine.png' },
  { id: 60, name: 'ニョロモ', keyword: ['ニョロモ'], image: '/pokemon-ierukana/assets/images/060Poliwag.png' },
  { id: 61, name: 'ニョロゾ', keyword: ['ニョロゾ'], image: '/pokemon-ierukana/assets/images/061Poliwhirl.png' },
  { id: 62, name: 'ニョロボン', keyword: ['ニョロボン'], image: '/pokemon-ierukana/assets/images/062Poliwrath.png' },
  { id: 63, name: 'ケーシィ', keyword: ['ケーシィ'], image: '/pokemon-ierukana/assets/images/063Abra.png' },
  { id: 64, name: 'ユンゲラー', keyword: ['ユンゲラー'], image: '/pokemon-ierukana/assets/images/064Kadabra.png' },
  { id: 65, name: 'フーディン', keyword: ['フーディン'], image: '/pokemon-ierukana/assets/images/065Alakazam.png' },
  { id: 66, name: 'ワンリキー', keyword: ['ワンリキー'], image: '/pokemon-ierukana/assets/images/066Machop.png' },
  { id: 67, name: 'ゴーリキー', keyword: ['ゴーリキー'], image: '/pokemon-ierukana/assets/images/067Machoke.png' },
  { id: 68, name: 'カイリキー', keyword: ['カイリキー'], image: '/pokemon-ierukana/assets/images/068Machamp.png' },
  { id: 69, name: 'マダツボミ', keyword: ['マダツボミ'], image: '/pokemon-ierukana/assets/images/069Bellsprout.png' },
  { id: 70, name: 'ウツドン', keyword: ['ウツドン'], image: '/pokemon-ierukana/assets/images/070Weepinbell.png' },
  { id: 71, name: 'ウツボット', keyword: ['ウツボット'], image: '/pokemon-ierukana/assets/images/071Victreebel.png' },
  { id: 72, name: 'メノクラゲ', keyword: ['メノクラゲ'], image: '/pokemon-ierukana/assets/images/072Tentacool.png' },
  { id: 73, name: 'ドククラゲ', keyword: ['ドククラゲ'], image: '/pokemon-ierukana/assets/images/073Tentacruel.png' },
  { id: 74, name: 'イシツブテ', keyword: ['イシツブテ'], image: '/pokemon-ierukana/assets/images/074Geodude.png' },
  { id: 75, name: 'ゴローン', keyword: ['ゴローン'], image: '/pokemon-ierukana/assets/images/075Graveler.png' },
  { id: 76, name: 'ゴローニャ', keyword: ['ゴローニャ'], image: '/pokemon-ierukana/assets/images/076Golem.png' },
  { id: 77, name: 'ポニータ', keyword: ['ポニータ'], image: '/pokemon-ierukana/assets/images/077Ponyta.png' },
  { id: 78, name: 'ギャロップ', keyword: ['ギャロップ'], image: '/pokemon-ierukana/assets/images/078Rapidash.png' },
  { id: 79, name: 'ヤドン', keyword: ['ヤドン'], image: '/pokemon-ierukana/assets/images/079Slowpoke.png' },
  { id: 80, name: 'ヤドラン', keyword: ['ヤドラン'], image: '/pokemon-ierukana/assets/images/080Slowbro.png' },
  { id: 81, name: 'コイル', keyword: ['コイル'], image: '/pokemon-ierukana/assets/images/081Magnemite.png' },
  { id: 82, name: 'レアコイル', keyword: ['レアコイル'], image: '/pokemon-ierukana/assets/images/082Magneton.png' },
  { id: 83, name: 'カモネギ', keyword: ['カモネギ'], image: '/pokemon-ierukana/assets/images/083Farfetchd.png' },
  { id: 84, name: 'ドードー', keyword: ['ドードー'], image: '/pokemon-ierukana/assets/images/084Doduo.png' },
  { id: 85, name: 'ドードリオ', keyword: ['ドードリオ'], image: '/pokemon-ierukana/assets/images/085Dodrio.png' },
  { id: 86, name: 'パウワウ', keyword: ['パウワウ'], image: '/pokemon-ierukana/assets/images/086Seel.png' },
  { id: 87, name: 'ジュゴン', keyword: ['ジュゴン'], image: '/pokemon-ierukana/assets/images/087Dewgong.png' },
  { id: 88, name: 'ベトベター', keyword: ['ベトベター'], image: '/pokemon-ierukana/assets/images/088Grimer.png' },
  { id: 89, name: 'ベトベトン', keyword: ['ベトベトン'], image: '/pokemon-ierukana/assets/images/089Muk.png' },
  { id: 90, name: 'シェルダー', keyword: ['シェルダー'], image: '/pokemon-ierukana/assets/images/090Shellder.png' },
  { id: 91, name: 'パルシェン', keyword: ['パルシェン'], image: '/pokemon-ierukana/assets/images/091Cloyster.png' },
  { id: 92, name: 'ゴース', keyword: ['ゴース'], image: '/pokemon-ierukana/assets/images/092Gastly.png' },
  { id: 93, name: 'ゴースト', keyword: ['ゴースト'], image: '/pokemon-ierukana/assets/images/093Haunter.png' },
  { id: 94, name: 'ゲンガー', keyword: ['ゲンガー'], image: '/pokemon-ierukana/assets/images/094Gengar.png' },
  { id: 95, name: 'イワーク', keyword: ['イワーク'], image: '/pokemon-ierukana/assets/images/095Onix.png' },
  { id: 96, name: 'スリープ', keyword: ['スリープ'], image: '/pokemon-ierukana/assets/images/096Drowzee.png' },
  { id: 97, name: 'スリーパー', keyword: ['スリーパー'], image: '/pokemon-ierukana/assets/images/097Hypno.png' },
  { id: 98, name: 'クラブ', keyword: ['クラブ'], image: '/pokemon-ierukana/assets/images/098Krabby.png' },
  { id: 99, name: 'キングラー', keyword: ['キングラー'], image: '/pokemon-ierukana/assets/images/099Kingler.png' },
  { id: 100, name: 'ビリリダマ', keyword: ['ビリリダマ'], image: '/pokemon-ierukana/assets/images/100Voltorb.png' },
  { id: 101, name: 'マルマイン', keyword: ['マルマイン'], image: '/pokemon-ierukana/assets/images/101Electrode.png' },
  { id: 102, name: 'タマタマ', keyword: ['タマタマ'], image: '/pokemon-ierukana/assets/images/102Exeggcute.png' },
  { id: 103, name: 'ナッシー', keyword: ['ナッシー'], image: '/pokemon-ierukana/assets/images/103Exeggutor.png' },
  { id: 104, name: 'カラカラ', keyword: ['カラカラ'], image: '/pokemon-ierukana/assets/images/104Cubone.png' },
  { id: 105, name: 'ガラガラ', keyword: ['ガラガラ'], image: '/pokemon-ierukana/assets/images/105Marowak.png' },
  { id: 106, name: 'サワムラー', keyword: ['サワムラー'], image: '/pokemon-ierukana/assets/images/106Hitmonlee.png' },
  { id: 107, name: 'エビワラー', keyword: ['エビワラー'], image: '/pokemon-ierukana/assets/images/107Hitmonchan.png' },
  { id: 108, name: 'ベロリンガ', keyword: ['ベロリンガ'], image: '/pokemon-ierukana/assets/images/108Lickitung.png' },
  { id: 109, name: 'ドガース', keyword: ['ドガース'], image: '/pokemon-ierukana/assets/images/109Koffing.png' },
  { id: 110, name: 'マタドガス', keyword: ['マタドガス'], image: '/pokemon-ierukana/assets/images/110Weezing.png' },
  { id: 111, name: 'サイホーン', keyword: ['サイホーン'], image: '/pokemon-ierukana/assets/images/111Rhyhorn.png' },
  { id: 112, name: 'サイドン', keyword: ['サイドン'], image: '/pokemon-ierukana/assets/images/112Rhydon.png' },
  { id: 113, name: 'ラッキー', keyword: ['ラッキー'], image: '/pokemon-ierukana/assets/images/113Chansey.png' },
  { id: 114, name: 'モンジャラ', keyword: ['モンジャラ'], image: '/pokemon-ierukana/assets/images/114Tangela.png' },
  { id: 115, name: 'ガルーラ', keyword: ['ガルーラ'], image: '/pokemon-ierukana/assets/images/115Kangaskhan.png' },
  { id: 116, name: 'タッツー', keyword: ['タッツー'], image: '/pokemon-ierukana/assets/images/116Horsea.png' },
  { id: 117, name: 'シードラ', keyword: ['シードラ'], image: '/pokemon-ierukana/assets/images/117Seadra.png' },
  { id: 118, name: 'トサキント', keyword: ['トサキント'], image: '/pokemon-ierukana/assets/images/118Goldeen.png' },
  { id: 119, name: 'アズマオウ', keyword: ['アズマオウ'], image: '/pokemon-ierukana/assets/images/119Seaking.png' },
  { id: 120, name: 'ヒトデマン', keyword: ['ヒトデマン'], image: '/pokemon-ierukana/assets/images/120Staryu.png' },
  { id: 121, name: 'スターミー', keyword: ['スターミー'], image: '/pokemon-ierukana/assets/images/121Starmie.png' },
  { id: 122, name: 'バリヤード', keyword: ['バリヤード'], image: '/pokemon-ierukana/assets/images/122Mr_Mime.png' },
  { id: 123, name: 'ストライク', keyword: ['ストライク'], image: '/pokemon-ierukana/assets/images/123Scyther.png' },
  { id: 124, name: 'ルージュラ', keyword: ['ルージュラ'], image: '/pokemon-ierukana/assets/images/124Jynx.png' },
  { id: 125, name: 'エレブー', keyword: ['エレブー'], image: '/pokemon-ierukana/assets/images/125Electabuzz.png' },
  { id: 126, name: 'ブーバー', keyword: ['ブーバー'], image: '/pokemon-ierukana/assets/images/126Magmar.png' },
  { id: 127, name: 'カイロス', keyword: ['カイロス'], image: '/pokemon-ierukana/assets/images/127Pinsir.png' },
  { id: 128, name: 'ケンタロス', keyword: ['ケンタロス'], image: '/pokemon-ierukana/assets/images/128Tauros.png' },
  { id: 129, name: 'コイキング', keyword: ['コイキング'], image: '/pokemon-ierukana/assets/images/129Magikarp.png' },
  { id: 130, name: 'ギャラドス', keyword: ['ギャラドス'], image: '/pokemon-ierukana/assets/images/130Gyarados.png' },
  { id: 131, name: 'ラプラス', keyword: ['ラプラス'], image: '/pokemon-ierukana/assets/images/131Lapras.png' },
  { id: 132, name: 'メタモン', keyword: ['メタモン'], image: '/pokemon-ierukana/assets/images/132Ditto.png' },
  { id: 133, name: 'イーブイ', keyword: ['イーブイ'], image: '/pokemon-ierukana/assets/images/133Eevee.png' },
  { id: 134, name: 'シャワーズ', keyword: ['シャワーズ'], image: '/pokemon-ierukana/assets/images/134Vaporeon.png' },
  { id: 135, name: 'サンダース', keyword: ['サンダース'], image: '/pokemon-ierukana/assets/images/135Jolteon.png' },
  { id: 136, name: 'ブースター', keyword: ['ブースター'], image: '/pokemon-ierukana/assets/images/136Flareon.png' },
  { id: 137, name: 'ポリゴン', keyword: ['ポリゴン'], image: '/pokemon-ierukana/assets/images/137Porygon.png' },
  { id: 138, name: 'オムナイト', keyword: ['オムナイト'], image: '/pokemon-ierukana/assets/images/138Omanyte.png' },
  { id: 139, name: 'オムスター', keyword: ['オムスター'], image: '/pokemon-ierukana/assets/images/139Omastar.png' },
  { id: 140, name: 'カブト', keyword: ['カブト'], image: '/pokemon-ierukana/assets/images/140Kabuto.png' },
  { id: 141, name: 'カブトプス', keyword: ['カブトプス'], image: '/pokemon-ierukana/assets/images/141Kabutops.png' },
  { id: 142, name: 'プテラ', keyword: ['プテラ'], image: '/pokemon-ierukana/assets/images/142Aerodactyl.png' },
  { id: 143, name: 'カビゴン', keyword: ['カビゴン'], image: '/pokemon-ierukana/assets/images/143Snorlax.png' },
  { id: 144, name: 'フリーザー', keyword: ['フリーザー'], image: '/pokemon-ierukana/assets/images/144Articuno.png' },
  { id: 145, name: 'サンダー', keyword: ['サンダー'], image: '/pokemon-ierukana/assets/images/145Zapdos.png' },
  { id: 146, name: 'ファイヤー', keyword: ['ファイヤー'], image: '/pokemon-ierukana/assets/images/146Moltres.png' },
  { id: 147, name: 'ミニリュウ', keyword: ['ミニリュウ'], image: '/pokemon-ierukana/assets/images/147Dratini.png' },
  { id: 148, name: 'ハクリュー', keyword: ['ハクリュー'], image: '/pokemon-ierukana/assets/images/148Dragonair.png' },
  { id: 149, name: 'カイリュー', keyword: ['カイリュー'], image: '/pokemon-ierukana/assets/images/149Dragonite.png' },
  { id: 150, name: 'ミュウツー', keyword: ['ミュウツー'], image: '/pokemon-ierukana/assets/images/150Mewtwo.png' },
  { id: 151, name: 'ミュウ', keyword: ['ミュウ'], image: '/pokemon-ierukana/assets/images/151Mew.png' },
  { id: 152, name: 'チコリータ', keyword: ['チコリータ'], image: '/pokemon-ierukana/assets/images/152Chikorita.png' },
  { id: 153, name: 'ベイリーフ', keyword: ['ベイリーフ'], image: '/pokemon-ierukana/assets/images/153Bayleef.png' },
  { id: 154, name: 'メガニウム', keyword: ['メガニウム'], image: '/pokemon-ierukana/assets/images/154Meganium.png' },
  { id: 155, name: 'ヒノアラシ', keyword: ['ヒノアラシ'], image: '/pokemon-ierukana/assets/images/155Cyndaquil.png' },
  { id: 156, name: 'マグマラシ', keyword: ['マグマラシ'], image: '/pokemon-ierukana/assets/images/156Quilava.png' },
  { id: 157, name: 'バクフーン', keyword: ['バクフーン'], image: '/pokemon-ierukana/assets/images/157Typhlosion.png' },
  { id: 158, name: 'ワニノコ', keyword: ['ワニノコ'], image: '/pokemon-ierukana/assets/images/158Totodile.png' },
  { id: 159, name: 'アリゲイツ', keyword: ['アリゲイツ'], image: '/pokemon-ierukana/assets/images/159Croconaw.png' },
  { id: 160, name: 'オーダイル', keyword: ['オーダイル'], image: '/pokemon-ierukana/assets/images/160Feraligatr.png' },
  { id: 161, name: 'オタチ', keyword: ['オタチ'], image: '/pokemon-ierukana/assets/images/161Sentret.png' },
  { id: 162, name: 'オオタチ', keyword: ['オオタチ'], image: '/pokemon-ierukana/assets/images/162Furret.png' },
  { id: 163, name: 'ホーホー', keyword: ['ホーホー'], image: '/pokemon-ierukana/assets/images/163Hoothoot.png' },
  { id: 164, name: 'ヨルノズク', keyword: ['ヨルノズク'], image: '/pokemon-ierukana/assets/images/164Noctowl.png' },
  { id: 165, name: 'レディバ', keyword: ['レディバ'], image: '/pokemon-ierukana/assets/images/165Ledyba.png' },
  { id: 166, name: 'レディアン', keyword: ['レディアン'], image: '/pokemon-ierukana/assets/images/166Ledian.png' },
  { id: 167, name: 'イトマル', keyword: ['イトマル'], image: '/pokemon-ierukana/assets/images/167Spinarak.png' },
  { id: 168, name: 'アリアドス', keyword: ['アリアドス'], image: '/pokemon-ierukana/assets/images/168Ariados.png' },
  { id: 169, name: 'クロバット', keyword: ['クロバット'], image: '/pokemon-ierukana/assets/images/169Crobat.png' },
  { id: 170, name: 'チョンチー', keyword: ['チョンチー'], image: '/pokemon-ierukana/assets/images/170Chinchou.png' },
  { id: 171, name: 'ランターン', keyword: ['ランターン'], image: '/pokemon-ierukana/assets/images/171Lanturn.png' },
  { id: 172, name: 'ピチュー', keyword: ['ピチュー'], image: '/pokemon-ierukana/assets/images/172Pichu.png' },
  { id: 173, name: 'ピィ', keyword: ['ピィ'], image: '/pokemon-ierukana/assets/images/173Cleffa.png' },
  { id: 174, name: 'ププリン', keyword: ['ププリン'], image: '/pokemon-ierukana/assets/images/174Igglybuff.png' },
  { id: 175, name: 'トゲピー', keyword: ['トゲピー'], image: '/pokemon-ierukana/assets/images/175Togepi.png' },
  { id: 176, name: 'トゲチック', keyword: ['トゲチック'], image: '/pokemon-ierukana/assets/images/176Togetic.png' },
  { id: 177, name: 'ネイティ', keyword: ['ネイティ'], image: '/pokemon-ierukana/assets/images/177Natu.png' },
  { id: 178, name: 'ネイティオ', keyword: ['ネイティオ'], image: '/pokemon-ierukana/assets/images/178Xatu.png' },
  { id: 179, name: 'メリープ', keyword: ['メリープ'], image: '/pokemon-ierukana/assets/images/179Mareep.png' },
  { id: 180, name: 'モココ', keyword: ['モココ'], image: '/pokemon-ierukana/assets/images/180Flaaffy.png' },
  { id: 181, name: 'デンリュウ', keyword: ['デンリュウ'], image: '/pokemon-ierukana/assets/images/181Ampharos.png' },
  { id: 182, name: 'キレイハナ', keyword: ['キレイハナ'], image: '/pokemon-ierukana/assets/images/182Bellossom.png' },
  { id: 183, name: 'マリル', keyword: ['マリル'], image: '/pokemon-ierukana/assets/images/183Marill.png' },
  { id: 184, name: 'マリルリ', keyword: ['マリルリ'], image: '/pokemon-ierukana/assets/images/184Azumarill.png' },
  { id: 185, name: 'ウソッキー', keyword: ['ウソッキー'], image: '/pokemon-ierukana/assets/images/185Sudowoodo.png' },
  { id: 186, name: 'ニョロトノ', keyword: ['ニョロトノ'], image: '/pokemon-ierukana/assets/images/186Politoed.png' },
  { id: 187, name: 'ハネッコ', keyword: ['ハネッコ'], image: '/pokemon-ierukana/assets/images/187Hoppip.png' },
  { id: 188, name: 'ポポッコ', keyword: ['ポポッコ'], image: '/pokemon-ierukana/assets/images/188Skiploom.png' },
  { id: 189, name: 'ワタッコ', keyword: ['ワタッコ'], image: '/pokemon-ierukana/assets/images/189Jumpluff.png' },
  { id: 190, name: 'エイパム', keyword: ['エイパム'], image: '/pokemon-ierukana/assets/images/190Aipom.png' },
  { id: 191, name: 'ヒマナッツ', keyword: ['ヒマナッツ'], image: '/pokemon-ierukana/assets/images/191Sunkern.png' },
  { id: 192, name: 'キマワリ', keyword: ['キマワリ'], image: '/pokemon-ierukana/assets/images/192Sunflora.png' },
  { id: 193, name: 'ヤンヤンマ', keyword: ['ヤンヤンマ'], image: '/pokemon-ierukana/assets/images/193Yanma.png' },
  { id: 194, name: 'ウパー', keyword: ['ウパー'], image: '/pokemon-ierukana/assets/images/194Wooper.png' },
  { id: 195, name: 'ヌオー', keyword: ['ヌオー'], image: '/pokemon-ierukana/assets/images/195Quagsire.png' },
  { id: 196, name: 'エーフィ', keyword: ['エーフィ'], image: '/pokemon-ierukana/assets/images/196Espeon.png' },
  { id: 197, name: 'ブラッキー', keyword: ['ブラッキー'], image: '/pokemon-ierukana/assets/images/197Umbreon.png' },
  { id: 198, name: 'ヤミカラス', keyword: ['ヤミカラス'], image: '/pokemon-ierukana/assets/images/198Murkrow.png' },
  { id: 199, name: 'ヤドキング', keyword: ['ヤドキング'], image: '/pokemon-ierukana/assets/images/199Slowking.png' },
  { id: 200, name: 'ムウマ', keyword: ['ムウマ'], image: '/pokemon-ierukana/assets/images/200Misdreavus.png' },
  { id: 201, name: 'アンノーン', keyword: ['アンノーン'], image: '/pokemon-ierukana/assets/images/201Unown.png' },
  { id: 202, name: 'ソーナンス', keyword: ['ソーナンス'], image: '/pokemon-ierukana/assets/images/202Wobbuffet.png' },
  { id: 203, name: 'キリンリキ', keyword: ['キリンリキ'], image: '/pokemon-ierukana/assets/images/203Girafarig.png' },
  { id: 204, name: 'クヌギダマ', keyword: ['クヌギダマ'], image: '/pokemon-ierukana/assets/images/204Pineco.png' },
  { id: 205, name: 'フォレトス', keyword: ['フォレトス'], image: '/pokemon-ierukana/assets/images/205Forretress.png' },
  { id: 206, name: 'ノコッチ', keyword: ['ノコッチ'], image: '/pokemon-ierukana/assets/images/206Dunsparce.png' },
  { id: 207, name: 'グライガー', keyword: ['グライガー'], image: '/pokemon-ierukana/assets/images/207Gligar.png' },
  { id: 208, name: 'ハガネール', keyword: ['ハガネール'], image: '/pokemon-ierukana/assets/images/208Steelix.png' },
  { id: 209, name: 'ブルー', keyword: ['ブルー'], image: '/pokemon-ierukana/assets/images/209Snubbull.png' },
  { id: 210, name: 'グランブル', keyword: ['グランブル'], image: '/pokemon-ierukana/assets/images/210Granbull.png' },
  { id: 211, name: 'ハリーセン', keyword: ['ハリーセン'], image: '/pokemon-ierukana/assets/images/211Qwilfish.png' },
  { id: 212, name: 'ハッサム', keyword: ['ハッサム'], image: '/pokemon-ierukana/assets/images/212Scizor.png' },
  { id: 213, name: 'ツボツボ', keyword: ['ツボツボ'], image: '/pokemon-ierukana/assets/images/213Shuckle.png' },
  { id: 214, name: 'ヘラクロス', keyword: ['ヘラクロス'], image: '/pokemon-ierukana/assets/images/214Heracross.png' },
  { id: 215, name: 'ニューラ', keyword: ['ニューラ'], image: '/pokemon-ierukana/assets/images/215Sneasel.png' },
  { id: 216, name: 'ヒメグマ', keyword: ['ヒメグマ'], image: '/pokemon-ierukana/assets/images/216Teddiursa.png' },
  { id: 217, name: 'リングマ', keyword: ['リングマ'], image: '/pokemon-ierukana/assets/images/217Ursaring.png' },
  { id: 218, name: 'マグマッグ', keyword: ['マグマッグ'], image: '/pokemon-ierukana/assets/images/218Slugma.png' },
  { id: 219, name: 'マグカルゴ', keyword: ['マグカルゴ'], image: '/pokemon-ierukana/assets/images/219Magcargo.png' },
  { id: 220, name: 'ウリムー', keyword: ['ウリムー'], image: '/pokemon-ierukana/assets/images/220Swinub.png' },
  { id: 221, name: 'イノムー', keyword: ['イノムー'], image: '/pokemon-ierukana/assets/images/221Piloswine.png' },
  { id: 222, name: 'サニーゴ', keyword: ['サニーゴ'], image: '/pokemon-ierukana/assets/images/222Corsola.png' },
  { id: 223, name: 'テッポウオ', keyword: ['テッポウオ'], image: '/pokemon-ierukana/assets/images/223Remoraid.png' },
  { id: 224, name: 'オクタン', keyword: ['オクタン'], image: '/pokemon-ierukana/assets/images/224Octillery.png' },
  { id: 225, name: 'デリバード', keyword: ['デリバード'], image: '/pokemon-ierukana/assets/images/225Delibird.png' },
  { id: 226, name: 'マンタイン', keyword: ['マンタイン'], image: '/pokemon-ierukana/assets/images/226Mantine.png' },
  { id: 227, name: 'エアームド', keyword: ['エアームド'], image: '/pokemon-ierukana/assets/images/227Skarmory.png' },
  { id: 228, name: 'デルビル', keyword: ['デルビル'], image: '/pokemon-ierukana/assets/images/228Houndour.png' },
  { id: 229, name: 'ヘルガー', keyword: ['ヘルガー'], image: '/pokemon-ierukana/assets/images/229Houndoom.png' },
  { id: 230, name: 'キングドラ', keyword: ['キングドラ'], image: '/pokemon-ierukana/assets/images/230Kingdra.png' },
  { id: 231, name: 'ゴマゾウ', keyword: ['ゴマゾウ'], image: '/pokemon-ierukana/assets/images/231Phanpy.png' },
  { id: 232, name: 'ドンファン', keyword: ['ドンファン'], image: '/pokemon-ierukana/assets/images/232Donphan.png' },
  { id: 233, name: 'ポリゴン２', keyword: ['ポリゴン２', 'ポリゴン2'], image: '/pokemon-ierukana/assets/images/233Porygon2.png' },
  { id: 234, name: 'オドシシ', keyword: ['オドシシ'], image: '/pokemon-ierukana/assets/images/234Stantler.png' },
  { id: 235, name: 'ドーブル', keyword: ['ドーブル'], image: '/pokemon-ierukana/assets/images/235Smeargle.png' },
  { id: 236, name: 'バルキー', keyword: ['バルキー'], image: '/pokemon-ierukana/assets/images/236Tyrogue.png' },
  { id: 237, name: 'カポエラー', keyword: ['カポエラー'], image: '/pokemon-ierukana/assets/images/237Hitmontop.png' },
  { id: 238, name: 'ムチュール', keyword: ['ムチュール'], image: '/pokemon-ierukana/assets/images/238Smoochum.png' },
  { id: 239, name: 'エレキッド', keyword: ['エレキッド'], image: '/pokemon-ierukana/assets/images/239Elekid.png' },
  { id: 240, name: 'ブビィ', keyword: ['ブビィ'], image: '/pokemon-ierukana/assets/images/240Magby.png' },
  { id: 241, name: 'ミルタンク', keyword: ['ミルタンク'], image: '/pokemon-ierukana/assets/images/241Miltank.png' },
  { id: 242, name: 'ハピナス', keyword: ['ハピナス'], image: '/pokemon-ierukana/assets/images/242Blissey.png' },
  { id: 243, name: 'ライコウ', keyword: ['ライコウ'], image: '/pokemon-ierukana/assets/images/243Raikou.png' },
  { id: 244, name: 'エンテイ', keyword: ['エンテイ'], image: '/pokemon-ierukana/assets/images/244Entei.png' },
  { id: 245, name: 'スイクン', keyword: ['スイクン'], image: '/pokemon-ierukana/assets/images/245Suicune.png' },
  { id: 246, name: 'ヨーギラス', keyword: ['ヨーギラス'], image: '/pokemon-ierukana/assets/images/246Larvitar.png' },
  { id: 247, name: 'サナギラス', keyword: ['サナギラス'], image: '/pokemon-ierukana/assets/images/247Pupitar.png' },
  { id: 248, name: 'バンギラス', keyword: ['バンギラス'], image: '/pokemon-ierukana/assets/images/248Tyranitar.png' },
  { id: 249, name: 'ルギア', keyword: ['ルギア'], image: '/pokemon-ierukana/assets/images/249Lugia.png' },
  { id: 250, name: 'ホウオウ', keyword: ['ホウオウ'], image: '/pokemon-ierukana/assets/images/250Ho-Oh.png' },
  { id: 251, name: 'セレビィ', keyword: ['セレビィ'], image: '/pokemon-ierukana/assets/images/251Celebi.png' },
  { id: 252, name: 'キモリ', keyword: ['キモリ'], image: '/pokemon-ierukana/assets/images/252Treecko.png' },
  { id: 253, name: 'ジュプトル', keyword: ['ジュプトル'], image: '/pokemon-ierukana/assets/images/253Grovyle.png' },
  { id: 254, name: 'ジュカイン', keyword: ['ジュカイン'], image: '/pokemon-ierukana/assets/images/254Sceptile.png' },
  { id: 255, name: 'アチャモ', keyword: ['アチャモ'], image: '/pokemon-ierukana/assets/images/255Torchic.png' },
  { id: 256, name: 'ワカシャモ', keyword: ['ワカシャモ'], image: '/pokemon-ierukana/assets/images/256Combusken.png' },
  { id: 257, name: 'バシャーモ', keyword: ['バシャーモ'], image: '/pokemon-ierukana/assets/images/257Blaziken.png' },
  { id: 258, name: 'ミズゴロウ', keyword: ['ミズゴロウ'], image: '/pokemon-ierukana/assets/images/258Mudkip.png' },
  { id: 259, name: 'ヌマクロー', keyword: ['ヌマクロー'], image: '/pokemon-ierukana/assets/images/259Marshtomp.png' },
  { id: 260, name: 'ラグラージ', keyword: ['ラグラージ'], image: '/pokemon-ierukana/assets/images/260Swampert.png' },
  { id: 261, name: 'ポチエナ', keyword: ['ポチエナ'], image: '/pokemon-ierukana/assets/images/261Poochyena.png' },
  { id: 262, name: 'グラエナ', keyword: ['グラエナ'], image: '/pokemon-ierukana/assets/images/262Mightyena.png' },
  { id: 263, name: 'ジグザグマ', keyword: ['ジグザグマ'], image: '/pokemon-ierukana/assets/images/263Zigzagoon.png' },
  { id: 264, name: 'マッスグマ', keyword: ['マッスグマ'], image: '/pokemon-ierukana/assets/images/264Linoone.png' },
  { id: 265, name: 'ケムッソ', keyword: ['ケムッソ'], image: '/pokemon-ierukana/assets/images/265Wurmple.png' },
  { id: 266, name: 'カラサリス', keyword: ['カラサリス'], image: '/pokemon-ierukana/assets/images/266Silcoon.png' },
  { id: 267, name: 'アゲハント', keyword: ['アゲハント'], image: '/pokemon-ierukana/assets/images/267Beautifly.png' },
  { id: 268, name: 'マユルド', keyword: ['マユルド'], image: '/pokemon-ierukana/assets/images/268Cascoon.png' },
  { id: 269, name: 'ドクケイル', keyword: ['ドクケイル'], image: '/pokemon-ierukana/assets/images/269Dustox.png' },
  { id: 270, name: 'ハスボー', keyword: ['ハスボー'], image: '/pokemon-ierukana/assets/images/270Lotad.png' },
  { id: 271, name: 'ハスブレロ', keyword: ['ハスブレロ'], image: '/pokemon-ierukana/assets/images/271Lombre.png' },
  { id: 272, name: 'ルンパッパ', keyword: ['ルンパッパ'], image: '/pokemon-ierukana/assets/images/272Ludicolo.png' },
  { id: 273, name: 'タネボー', keyword: ['タネボー'], image: '/pokemon-ierukana/assets/images/273Seedot.png' },
  { id: 274, name: 'コノハナ', keyword: ['コノハナ'], image: '/pokemon-ierukana/assets/images/274Nuzleaf.png' },
  { id: 275, name: 'ダーテング', keyword: ['ダーテング'], image: '/pokemon-ierukana/assets/images/275Shiftry.png' },
  { id: 276, name: 'スバメ', keyword: ['スバメ'], image: '/pokemon-ierukana/assets/images/276Taillow.png' },
  { id: 277, name: 'オオスバメ', keyword: ['オオスバメ'], image: '/pokemon-ierukana/assets/images/277Swellow.png' },
  { id: 278, name: 'キャモメ', keyword: ['キャモメ'], image: '/pokemon-ierukana/assets/images/278Wingull.png' },
  { id: 279, name: 'ペリッパー', keyword: ['ペリッパー'], image: '/pokemon-ierukana/assets/images/279Pelipper.png' },
  { id: 280, name: 'ラルトス', keyword: ['ラルトス'], image: '/pokemon-ierukana/assets/images/280Ralts.png' },
  { id: 281, name: 'キルリア', keyword: ['キルリア'], image: '/pokemon-ierukana/assets/images/281Kirlia.png' },
  { id: 282, name: 'サーナイト', keyword: ['サーナイト'], image: '/pokemon-ierukana/assets/images/282Gardevoir.png' },
  { id: 283, name: 'アメタマ', keyword: ['アメタマ'], image: '/pokemon-ierukana/assets/images/283Surskit.png' },
  { id: 284, name: 'アメモース', keyword: ['アメモース'], image: '/pokemon-ierukana/assets/images/284Masquerain.png' },
  { id: 285, name: 'キノココ', keyword: ['キノココ'], image: '/pokemon-ierukana/assets/images/285Shroomish.png' },
  { id: 286, name: 'キノガッサ', keyword: ['キノガッサ'], image: '/pokemon-ierukana/assets/images/286Breloom.png' },
  { id: 287, name: 'ナマケロ', keyword: ['ナマケロ'], image: '/pokemon-ierukana/assets/images/287Slakoth.png' },
  { id: 288, name: 'ヤルキモノ', keyword: ['ヤルキモノ'], image: '/pokemon-ierukana/assets/images/288Vigoroth.png' },
  { id: 289, name: 'ケッキング', keyword: ['ケッキング'], image: '/pokemon-ierukana/assets/images/289Slaking.png' },
  { id: 290, name: 'ツチニン', keyword: ['ツチニン'], image: '/pokemon-ierukana/assets/images/290Nincada.png' },
  { id: 291, name: 'テッカニン', keyword: ['テッカニン'], image: '/pokemon-ierukana/assets/images/291Ninjask.png' },
  { id: 292, name: 'ヌケニン', keyword: ['ヌケニン'], image: '/pokemon-ierukana/assets/images/292Shedinja.png' },
  { id: 293, name: 'ゴニョニョ', keyword: ['ゴニョニョ'], image: '/pokemon-ierukana/assets/images/293Whismur.png' },
  { id: 294, name: 'ドゴーム', keyword: ['ドゴーム'], image: '/pokemon-ierukana/assets/images/294Loudred.png' },
  { id: 295, name: 'バクオング', keyword: ['バクオング'], image: '/pokemon-ierukana/assets/images/295Exploud.png' },
  { id: 296, name: 'マクノシタ', keyword: ['マクノシタ'], image: '/pokemon-ierukana/assets/images/296Makuhita.png' },
  { id: 297, name: 'ハリテヤマ', keyword: ['ハリテヤマ'], image: '/pokemon-ierukana/assets/images/297Hariyama.png' },
  { id: 298, name: 'ルリリ', keyword: ['ルリリ'], image: '/pokemon-ierukana/assets/images/298Azurill.png' },
  { id: 299, name: 'ノズパス', keyword: ['ノズパス'], image: '/pokemon-ierukana/assets/images/299Nosepass.png' },
  { id: 300, name: 'エネコ', keyword: ['エネコ'], image: '/pokemon-ierukana/assets/images/300Skitty.png' },
  { id: 301, name: 'エネコロロ', keyword: ['エネコロロ'], image: '/pokemon-ierukana/assets/images/301Delcatty.png' },
  { id: 302, name: 'ヤミラミ', keyword: ['ヤミラミ'], image: '/pokemon-ierukana/assets/images/302Sableye.png' },
  { id: 303, name: 'クチート', keyword: ['クチート'], image: '/pokemon-ierukana/assets/images/303Mawile.png' },
  { id: 304, name: 'ココドラ', keyword: ['ココドラ'], image: '/pokemon-ierukana/assets/images/304Aron.png' },
  { id: 305, name: 'コドラ', keyword: ['コドラ'], image: '/pokemon-ierukana/assets/images/305Lairon.png' },
  { id: 306, name: 'ボスゴドラ', keyword: ['ボスゴドラ'], image: '/pokemon-ierukana/assets/images/306Aggron.png' },
  { id: 307, name: 'アサナン', keyword: ['アサナン'], image: '/pokemon-ierukana/assets/images/307Meditite.png' },
  { id: 308, name: 'チャーレム', keyword: ['チャーレム'], image: '/pokemon-ierukana/assets/images/308Medicham.png' },
  { id: 309, name: 'ラクライ', keyword: ['ラクライ'], image: '/pokemon-ierukana/assets/images/309Electrike.png' },
  { id: 310, name: 'ライボルト', keyword: ['ライボルト'], image: '/pokemon-ierukana/assets/images/310Manectric.png' },
  { id: 311, name: 'プラスル', keyword: ['プラスル'], image: '/pokemon-ierukana/assets/images/311Plusle.png' },
  { id: 312, name: 'マイナン', keyword: ['マイナン'], image: '/pokemon-ierukana/assets/images/312Minun.png' },
  { id: 313, name: 'バルビート', keyword: ['バルビート'], image: '/pokemon-ierukana/assets/images/313Volbeat.png' },
  { id: 314, name: 'イルミーゼ', keyword: ['イルミーゼ'], image: '/pokemon-ierukana/assets/images/314Illumise.png' },
  { id: 315, name: 'ロゼリア', keyword: ['ロゼリア'], image: '/pokemon-ierukana/assets/images/315Roselia.png' },
  { id: 316, name: 'ゴクリン', keyword: ['ゴクリン'], image: '/pokemon-ierukana/assets/images/316Gulpin.png' },
  { id: 317, name: 'マルノーム', keyword: ['マルノーム'], image: '/pokemon-ierukana/assets/images/317Swalot.png' },
  { id: 318, name: 'キバニア', keyword: ['キバニア'], image: '/pokemon-ierukana/assets/images/318Carvanha.png' },
  { id: 319, name: 'サメハダー', keyword: ['サメハダー'], image: '/pokemon-ierukana/assets/images/319Sharpedo.png' },
  { id: 320, name: 'ホエルコ', keyword: ['ホエルコ'], image: '/pokemon-ierukana/assets/images/320Wailmer.png' },
  { id: 321, name: 'ホエルオー', keyword: ['ホエルオー'], image: '/pokemon-ierukana/assets/images/321Wailord.png' },
  { id: 322, name: 'ドンメル', keyword: ['ドンメル'], image: '/pokemon-ierukana/assets/images/322Numel.png' },
  { id: 323, name: 'バクーダ', keyword: ['バクーダ'], image: '/pokemon-ierukana/assets/images/323Camerupt.png' },
  { id: 324, name: 'コータス', keyword: ['コータス'], image: '/pokemon-ierukana/assets/images/324Torkoal.png' },
  { id: 325, name: 'バネブー', keyword: ['バネブー'], image: '/pokemon-ierukana/assets/images/325Spoink.png' },
  { id: 326, name: 'ブーピッグ', keyword: ['ブーピッグ'], image: '/pokemon-ierukana/assets/images/326Grumpig.png' },
  { id: 327, name: 'パッチール', keyword: ['パッチール'], image: '/pokemon-ierukana/assets/images/327Spinda.png' },
  { id: 328, name: 'ナックラー', keyword: ['ナックラー'], image: '/pokemon-ierukana/assets/images/328Trapinch.png' },
  { id: 329, name: 'ビブラーバ', keyword: ['ビブラーバ'], image: '/pokemon-ierukana/assets/images/329Vibrava.png' },
  { id: 330, name: 'フライゴン', keyword: ['フライゴン'], image: '/pokemon-ierukana/assets/images/330Flygon.png' },
  { id: 331, name: 'サボネア', keyword: ['サボネア'], image: '/pokemon-ierukana/assets/images/331Cacnea.png' },
  { id: 332, name: 'ノクタス', keyword: ['ノクタス'], image: '/pokemon-ierukana/assets/images/332Cacturne.png' },
  { id: 333, name: 'チルット', keyword: ['チルット'], image: '/pokemon-ierukana/assets/images/333Swablu.png' },
  { id: 334, name: 'チルタリス', keyword: ['チルタリス'], image: '/pokemon-ierukana/assets/images/334Altaria.png' },
  { id: 335, name: 'ザングース', keyword: ['ザングース'], image: '/pokemon-ierukana/assets/images/335Zangoose.png' },
  { id: 336, name: 'ハブネーク', keyword: ['ハブネーク'], image: '/pokemon-ierukana/assets/images/336Seviper.png' },
  { id: 337, name: 'ルナトーン', keyword: ['ルナトーン'], image: '/pokemon-ierukana/assets/images/337Lunatone.png' },
  { id: 338, name: 'ソルロック', keyword: ['ソルロック'], image: '/pokemon-ierukana/assets/images/338Solrock.png' },
  { id: 339, name: 'ドジョッチ', keyword: ['ドジョッチ'], image: '/pokemon-ierukana/assets/images/339Barboach.png' },
  { id: 340, name: 'ナマズン', keyword: ['ナマズン'], image: '/pokemon-ierukana/assets/images/340Whiscash.png' },
  { id: 341, name: 'ヘイガニ', keyword: ['ヘイガニ'], image: '/pokemon-ierukana/assets/images/341Corphish.png' },
  { id: 342, name: 'シザリガー', keyword: ['シザリガー'], image: '/pokemon-ierukana/assets/images/342Crawdaunt.png' },
  { id: 343, name: 'ヤジロン', keyword: ['ヤジロン'], image: '/pokemon-ierukana/assets/images/343Baltoy.png' },
  { id: 344, name: 'ネンドール', keyword: ['ネンドール'], image: '/pokemon-ierukana/assets/images/344Claydol.png' },
  { id: 345, name: 'リリーラ', keyword: ['リリーラ'], image: '/pokemon-ierukana/assets/images/345Lileep.png' },
  { id: 346, name: 'ユレイドル', keyword: ['ユレイドル'], image: '/pokemon-ierukana/assets/images/346Cradily.png' },
  { id: 347, name: 'アノプス', keyword: ['アノプス'], image: '/pokemon-ierukana/assets/images/347Anorith.png' },
  { id: 348, name: 'アーマルド', keyword: ['アーマルド'], image: '/pokemon-ierukana/assets/images/348Armaldo.png' },
  { id: 349, name: 'ヒンバス', keyword: ['ヒンバス'], image: '/pokemon-ierukana/assets/images/349Feebas.png' },
  { id: 350, name: 'ミロカロス', keyword: ['ミロカロス'], image: '/pokemon-ierukana/assets/images/350Milotic.png' },
  { id: 351, name: 'ポワルン', keyword: ['ポワルン'], image: '/pokemon-ierukana/assets/images/351Castform.png' },
  { id: 352, name: 'カクレオン', keyword: ['カクレオン'], image: '/pokemon-ierukana/assets/images/352Kecleon.png' },
  { id: 353, name: 'カゲボウズ', keyword: ['カゲボウズ'], image: '/pokemon-ierukana/assets/images/353Shuppet.png' },
  { id: 354, name: 'ジュペッタ', keyword: ['ジュペッタ'], image: '/pokemon-ierukana/assets/images/354Banette.png' },
  { id: 355, name: 'ヨマワル', keyword: ['ヨマワル'], image: '/pokemon-ierukana/assets/images/355Duskull.png' },
  { id: 356, name: 'サマヨール', keyword: ['サマヨール'], image: '/pokemon-ierukana/assets/images/356Dusclops.png' },
  { id: 357, name: 'トロピウス', keyword: ['トロピウス'], image: '/pokemon-ierukana/assets/images/357Tropius.png' },
  { id: 358, name: 'チリーン', keyword: ['チリーン'], image: '/pokemon-ierukana/assets/images/358Chimecho.png' },
  { id: 359, name: 'アブソル', keyword: ['アブソル'], image: '/pokemon-ierukana/assets/images/359Absol.png' },
  { id: 360, name: 'ソーナノ', keyword: ['ソーナノ'], image: '/pokemon-ierukana/assets/images/360Wynaut.png' },
  { id: 361, name: 'ユキワラシ', keyword: ['ユキワラシ'], image: '/pokemon-ierukana/assets/images/361Snorunt.png' },
  { id: 362, name: 'オニゴーリ', keyword: ['オニゴーリ'], image: '/pokemon-ierukana/assets/images/362Glalie.png' },
  { id: 363, name: 'タマザラシ', keyword: ['タマザラシ'], image: '/pokemon-ierukana/assets/images/363Spheal.png' },
  { id: 364, name: 'トドグラー', keyword: ['トドグラー'], image: '/pokemon-ierukana/assets/images/364Sealeo.png' },
  { id: 365, name: 'トドゼルガ', keyword: ['トドゼルガ'], image: '/pokemon-ierukana/assets/images/365Walrein.png' },
  { id: 366, name: 'パールル', keyword: ['パールル'], image: '/pokemon-ierukana/assets/images/366Clamperl.png' },
  { id: 367, name: 'ハンテール', keyword: ['ハンテール'], image: '/pokemon-ierukana/assets/images/367Huntail.png' },
  { id: 368, name: 'サクラビス', keyword: ['サクラビス'], image: '/pokemon-ierukana/assets/images/368Gorebyss.png' },
  { id: 369, name: 'ジーランス', keyword: ['ジーランス'], image: '/pokemon-ierukana/assets/images/369Relicanth.png' },
  { id: 370, name: 'ラブカス', keyword: ['ラブカス'], image: '/pokemon-ierukana/assets/images/370Luvdisc.png' },
  { id: 371, name: 'タツベイ', keyword: ['タツベイ'], image: '/pokemon-ierukana/assets/images/371Bagon.png' },
  { id: 372, name: 'コモルー', keyword: ['コモルー'], image: '/pokemon-ierukana/assets/images/372Shelgon.png' },
  { id: 373, name: 'ボーマンダ', keyword: ['ボーマンダ'], image: '/pokemon-ierukana/assets/images/373Salamence.png' },
  { id: 374, name: 'ダンバル', keyword: ['ダンバル'], image: '/pokemon-ierukana/assets/images/374Beldum.png' },
  { id: 375, name: 'メタング', keyword: ['メタング'], image: '/pokemon-ierukana/assets/images/375Metang.png' },
  { id: 376, name: 'メタグロス', keyword: ['メタグロス'], image: '/pokemon-ierukana/assets/images/376Metagross.png' },
  { id: 377, name: 'レジロック', keyword: ['レジロック'], image: '/pokemon-ierukana/assets/images/377Regirock.png' },
  { id: 378, name: 'レジアイス', keyword: ['レジアイス'], image: '/pokemon-ierukana/assets/images/378Regice.png' },
  { id: 379, name: 'レジスチル', keyword: ['レジスチル'], image: '/pokemon-ierukana/assets/images/379Registeel.png' },
  { id: 380, name: 'ラティアス', keyword: ['ラティアス'], image: '/pokemon-ierukana/assets/images/380Latias.png' },
  { id: 381, name: 'ラティオス', keyword: ['ラティオス'], image: '/pokemon-ierukana/assets/images/381Latios.png' },
  { id: 382, name: 'カイオーガ', keyword: ['カイオーガ'], image: '/pokemon-ierukana/assets/images/382Kyogre.png' },
  { id: 383, name: 'グラードン', keyword: ['グラードン'], image: '/pokemon-ierukana/assets/images/383Groudon.png' },
  { id: 384, name: 'レックウザ', keyword: ['レックウザ'], image: '/pokemon-ierukana/assets/images/384Rayquaza.png' },
  { id: 385, name: 'ジラーチ', keyword: ['ジラーチ'], image: '/pokemon-ierukana/assets/images/385Jirachi.png' },
  { id: 386, name: 'デオキシス', keyword: ['デオキシス'], image: '/pokemon-ierukana/assets/images/386Deoxys.png' },
  { id: 387, name: 'ナエトル', keyword: ['ナエトル'], image: '/pokemon-ierukana/assets/images/387Turtwig.png' },
  { id: 388, name: 'ハヤシガメ', keyword: ['ハヤシガメ'], image: '/pokemon-ierukana/assets/images/388Grotle.png' },
  { id: 389, name: 'ドダイトス', keyword: ['ドダイトス'], image: '/pokemon-ierukana/assets/images/389Torterra.png' },
  { id: 390, name: 'ヒコザル', keyword: ['ヒコザル'], image: '/pokemon-ierukana/assets/images/390Chimchar.png' },
  { id: 391, name: 'モウカザル', keyword: ['モウカザル'], image: '/pokemon-ierukana/assets/images/391Monferno.png' },
  { id: 392, name: 'ゴウカザル', keyword: ['ゴウカザル'], image: '/pokemon-ierukana/assets/images/392Infernape.png' },
  { id: 393, name: 'ポッチャマ', keyword: ['ポッチャマ'], image: '/pokemon-ierukana/assets/images/393Piplup.png' },
  { id: 394, name: 'ポッタイシ', keyword: ['ポッタイシ'], image: '/pokemon-ierukana/assets/images/394Prinplup.png' },
  { id: 395, name: 'エンペルト', keyword: ['エンペルト'], image: '/pokemon-ierukana/assets/images/395Empoleon.png' },
  { id: 396, name: 'ムックル', keyword: ['ムックル'], image: '/pokemon-ierukana/assets/images/396Starly.png' },
  { id: 397, name: 'ムクバード', keyword: ['ムクバード'], image: '/pokemon-ierukana/assets/images/397Staravia.png' },
  { id: 398, name: 'ムクホーク', keyword: ['ムクホーク'], image: '/pokemon-ierukana/assets/images/398Staraptor.png' },
  { id: 399, name: 'ビッパ', keyword: ['ビッパ'], image: '/pokemon-ierukana/assets/images/399Bidoof.png' },
  { id: 400, name: 'ビーダル', keyword: ['ビーダル'], image: '/pokemon-ierukana/assets/images/400Bibarel.png' },
  { id: 401, name: 'コロボーシ', keyword: ['コロボーシ'], image: '/pokemon-ierukana/assets/images/401Kricketot.png' },
  { id: 402, name: 'コロトック', keyword: ['コロトック'], image: '/pokemon-ierukana/assets/images/402Kricketune.png' },
  { id: 403, name: 'コリンク', keyword: ['コリンク'], image: '/pokemon-ierukana/assets/images/403Shinx.png' },
  { id: 404, name: 'ルクシオ', keyword: ['ルクシオ'], image: '/pokemon-ierukana/assets/images/404Luxio.png' },
  { id: 405, name: 'レントラー', keyword: ['レントラー'], image: '/pokemon-ierukana/assets/images/405Luxray.png' },
  { id: 406, name: 'スボミー', keyword: ['スボミー'], image: '/pokemon-ierukana/assets/images/406Budew.png' },
  { id: 407, name: 'ロズレイド', keyword: ['ロズレイド'], image: '/pokemon-ierukana/assets/images/407Roserade.png' },
  { id: 408, name: 'ズガイドス', keyword: ['ズガイドス'], image: '/pokemon-ierukana/assets/images/408Cranidos.png' },
  { id: 409, name: 'ラムパルド', keyword: ['ラムパルド'], image: '/pokemon-ierukana/assets/images/409Rampardos.png' },
  { id: 410, name: 'タテトプス', keyword: ['タテトプス'], image: '/pokemon-ierukana/assets/images/410Shieldon.png' },
  { id: 411, name: 'トリデプス', keyword: ['トリデプス'], image: '/pokemon-ierukana/assets/images/411Bastiodon.png' },
  { id: 412, name: 'ミノムッチ', keyword: ['ミノムッチ'], image: '/pokemon-ierukana/assets/images/412Burmy.png' },
  { id: 413, name: 'ミノマダム', keyword: ['ミノマダム'], image: '/pokemon-ierukana/assets/images/413Wormadam.png' },
  { id: 414, name: 'ガーメイル', keyword: ['ガーメイル'], image: '/pokemon-ierukana/assets/images/414Mothim.png' },
  { id: 415, name: 'ミツハニー', keyword: ['ミツハニー'], image: '/pokemon-ierukana/assets/images/415Combee.png' },
  { id: 416, name: 'ビークイン', keyword: ['ビークイン'], image: '/pokemon-ierukana/assets/images/416Vespiquen.png' },
  { id: 417, name: 'パチリス', keyword: ['パチリス'], image: '/pokemon-ierukana/assets/images/417Pachirisu.png' },
  { id: 418, name: 'ブイゼル', keyword: ['ブイゼル'], image: '/pokemon-ierukana/assets/images/418Buizel.png' },
  { id: 419, name: 'フローゼル', keyword: ['フローゼル'], image: '/pokemon-ierukana/assets/images/419Floatzel.png' },
  { id: 420, name: 'チェリンボ', keyword: ['チェリンボ'], image: '/pokemon-ierukana/assets/images/420Cherubi.png' },
  { id: 421, name: 'チェリム', keyword: ['チェリム'], image: '/pokemon-ierukana/assets/images/421Cherrim.png' },
  { id: 422, name: 'カラナクシ', keyword: ['カラナクシ'], image: '/pokemon-ierukana/assets/images/422Shellos.png' },
  { id: 423, name: 'トリトドン', keyword: ['トリトドン'], image: '/pokemon-ierukana/assets/images/423Gastrodon.png' },
  { id: 424, name: 'エテボース', keyword: ['エテボース'], image: '/pokemon-ierukana/assets/images/424Ambipom.png' },
  { id: 425, name: 'フワンテ', keyword: ['フワンテ'], image: '/pokemon-ierukana/assets/images/425Drifloon.png' },
  { id: 426, name: 'フワライド', keyword: ['フワライド'], image: '/pokemon-ierukana/assets/images/426Drifblim.png' },
  { id: 427, name: 'ミミロル', keyword: ['ミミロル'], image: '/pokemon-ierukana/assets/images/427Buneary.png' },
  { id: 428, name: 'ミミロップ', keyword: ['ミミロップ'], image: '/pokemon-ierukana/assets/images/428Lopunny.png' },
  { id: 429, name: 'ムウマージ', keyword: ['ムウマージ'], image: '/pokemon-ierukana/assets/images/429Mismagius.png' },
  { id: 430, name: 'ドンカラス', keyword: ['ドンカラス'], image: '/pokemon-ierukana/assets/images/430Honchkrow.png' },
  { id: 431, name: 'ニャルマー', keyword: ['ニャルマー'], image: '/pokemon-ierukana/assets/images/431Glameow.png' },
  { id: 432, name: 'ブニャット', keyword: ['ブニャット'], image: '/pokemon-ierukana/assets/images/432Purugly.png' },
  { id: 433, name: 'リーシャン', keyword: ['リーシャン'], image: '/pokemon-ierukana/assets/images/433Chingling.png' },
  { id: 434, name: 'スカンプー', keyword: ['スカンプー'], image: '/pokemon-ierukana/assets/images/434Stunky.png' },
  { id: 435, name: 'スカタンク', keyword: ['スカタンク'], image: '/pokemon-ierukana/assets/images/435Skuntank.png' },
  { id: 436, name: 'ドーミラー', keyword: ['ドーミラー'], image: '/pokemon-ierukana/assets/images/436Bronzor.png' },
  { id: 437, name: 'ドータクン', keyword: ['ドータクン'], image: '/pokemon-ierukana/assets/images/437Bronzong.png' },
  { id: 438, name: 'ウソハチ', keyword: ['ウソハチ'], image: '/pokemon-ierukana/assets/images/438Bonsly.png' },
  { id: 439, name: 'マネネ', keyword: ['マネネ'], image: '/pokemon-ierukana/assets/images/439Mime_Jr.png' },
  { id: 440, name: 'ピンプク', keyword: ['ピンプク'], image: '/pokemon-ierukana/assets/images/440Happiny.png' },
  { id: 441, name: 'ペラップ', keyword: ['ペラップ'], image: '/pokemon-ierukana/assets/images/441Chatot.png' },
  { id: 442, name: 'ミカルゲ', keyword: ['ミカルゲ'], image: '/pokemon-ierukana/assets/images/442Spiritomb.png' },
  { id: 443, name: 'フカマル', keyword: ['フカマル'], image: '/pokemon-ierukana/assets/images/443Gible.png' },
  { id: 444, name: 'ガバイト', keyword: ['ガバイト'], image: '/pokemon-ierukana/assets/images/444Gabite.png' },
  { id: 445, name: 'ガブリアス', keyword: ['ガブリアス'], image: '/pokemon-ierukana/assets/images/445Garchomp.png' },
  { id: 446, name: 'ゴンベ', keyword: ['ゴンベ'], image: '/pokemon-ierukana/assets/images/446Munchlax.png' },
  { id: 447, name: 'リオル', keyword: ['リオル'], image: '/pokemon-ierukana/assets/images/447Riolu.png' },
  { id: 448, name: 'ルカリオ', keyword: ['ルカリオ'], image: '/pokemon-ierukana/assets/images/448Lucario.png' },
  { id: 449, name: 'ヒポポタス', keyword: ['ヒポポタス'], image: '/pokemon-ierukana/assets/images/449Hippopotas.png' },
  { id: 450, name: 'カバルドン', keyword: ['カバルドン'], image: '/pokemon-ierukana/assets/images/450Hippowdon.png' },
  { id: 451, name: 'スコルピ', keyword: ['スコルピ'], image: '/pokemon-ierukana/assets/images/451Skorupi.png' },
  { id: 452, name: 'ドラピオン', keyword: ['ドラピオン'], image: '/pokemon-ierukana/assets/images/452Drapion.png' },
  { id: 453, name: 'グレッグル', keyword: ['グレッグル'], image: '/pokemon-ierukana/assets/images/453Croagunk.png' },
  { id: 454, name: 'ドクロッグ', keyword: ['ドクロッグ'], image: '/pokemon-ierukana/assets/images/454Toxicroak.png' },
  { id: 455, name: 'マスキッパ', keyword: ['マスキッパ'], image: '/pokemon-ierukana/assets/images/455Carnivine.png' },
  { id: 456, name: 'ケイコウオ', keyword: ['ケイコウオ'], image: '/pokemon-ierukana/assets/images/456Finneon.png' },
  { id: 457, name: 'ネオラント', keyword: ['ネオラント'], image: '/pokemon-ierukana/assets/images/457Lumineon.png' },
  { id: 458, name: 'タマンタ', keyword: ['タマンタ'], image: '/pokemon-ierukana/assets/images/458Mantyke.png' },
  { id: 459, name: 'ユキカブリ', keyword: ['ユキカブリ'], image: '/pokemon-ierukana/assets/images/459Snover.png' },
  { id: 460, name: 'ユキノオー', keyword: ['ユキノオー'], image: '/pokemon-ierukana/assets/images/460Abomasnow.png' },
  { id: 461, name: 'マニューラ', keyword: ['マニューラ'], image: '/pokemon-ierukana/assets/images/461Weavile.png' },
  { id: 462, name: 'ジバコイル', keyword: ['ジバコイル'], image: '/pokemon-ierukana/assets/images/462Magnezone.png' },
  { id: 463, name: 'ベロベルト', keyword: ['ベロベルト'], image: '/pokemon-ierukana/assets/images/463Lickilicky.png' },
  { id: 464, name: 'ドサイドン', keyword: ['ドサイドン'], image: '/pokemon-ierukana/assets/images/464Rhyperior.png' },
  { id: 465, name: 'モジャンボ', keyword: ['モジャンボ'], image: '/pokemon-ierukana/assets/images/465Tangrowth.png' },
  { id: 466, name: 'エレキブル', keyword: ['エレキブル'], image: '/pokemon-ierukana/assets/images/466Electivire.png' },
  { id: 467, name: 'ブーバーン', keyword: ['ブーバーン'], image: '/pokemon-ierukana/assets/images/467Magmortar.png' },
  { id: 468, name: 'トゲキッス', keyword: ['トゲキッス'], image: '/pokemon-ierukana/assets/images/468Togekiss.png' },
  { id: 469, name: 'メガヤンマ', keyword: ['メガヤンマ'], image: '/pokemon-ierukana/assets/images/469Yanmega.png' },
  { id: 470, name: 'リーフィア', keyword: ['リーフィア'], image: '/pokemon-ierukana/assets/images/470Leafeon.png' },
  { id: 471, name: 'グレイシア', keyword: ['グレイシア'], image: '/pokemon-ierukana/assets/images/471Glaceon.png' },
  { id: 472, name: 'グライオン', keyword: ['グライオン'], image: '/pokemon-ierukana/assets/images/472Gliscor.png' },
  { id: 473, name: 'マンムー', keyword: ['マンムー'], image: '/pokemon-ierukana/assets/images/473Mamoswine.png' },
  { id: 474, name: 'ポリゴンＺ', keyword: ['ポリゴンＺ', 'ポリゴンz', 'ポリゴンゼット'], image: '/pokemon-ierukana/assets/images/474Porygon-Z.png' },
  { id: 475, name: 'エルレイド', keyword: ['エルレイド'], image: '/pokemon-ierukana/assets/images/475Gallade.png' },
  { id: 476, name: 'ダイノーズ', keyword: ['ダイノーズ'], image: '/pokemon-ierukana/assets/images/476Probopass.png' },
  { id: 477, name: 'ヨノワール', keyword: ['ヨノワール'], image: '/pokemon-ierukana/assets/images/477Dusknoir.png' },
  { id: 478, name: 'ユキメノコ', keyword: ['ユキメノコ'], image: '/pokemon-ierukana/assets/images/478Froslass.png' },
  { id: 479, name: 'ロトム', keyword: ['ロトム'], image: '/pokemon-ierukana/assets/images/479Rotom.png' },
  { id: 480, name: 'ユクシー', keyword: ['ユクシー'], image: '/pokemon-ierukana/assets/images/480Uxie.png' },
  { id: 481, name: 'エムリット', keyword: ['エムリット'], image: '/pokemon-ierukana/assets/images/481Mesprit.png' },
  { id: 482, name: 'アグノム', keyword: ['アグノム'], image: '/pokemon-ierukana/assets/images/482Azelf.png' },
  { id: 483, name: 'ディアルガ', keyword: ['ディアルガ'], image: '/pokemon-ierukana/assets/images/483Dialga.png' },
  { id: 484, name: 'パルキア', keyword: ['パルキア'], image: '/pokemon-ierukana/assets/images/484Palkia.png' },
  { id: 485, name: 'ヒードラン', keyword: ['ヒードラン'], image: '/pokemon-ierukana/assets/images/485Heatran.png' },
  { id: 486, name: 'レジギガス', keyword: ['レジギガス'], image: '/pokemon-ierukana/assets/images/486Regigigas.png' },
  { id: 487, name: 'ギラティナ', keyword: ['ギラティナ'], image: '/pokemon-ierukana/assets/images/487Giratina.png' },
  { id: 488, name: 'クレセリア', keyword: ['クレセリア'], image: '/pokemon-ierukana/assets/images/488Cresselia.png' },
  { id: 489, name: 'フィオネ', keyword: ['フィオネ'], image: '/pokemon-ierukana/assets/images/489Phione.png' },
  { id: 490, name: 'マナフィ', keyword: ['マナフィ'], image: '/pokemon-ierukana/assets/images/490Manaphy.png' },
  { id: 491, name: 'ダークライ', keyword: ['ダークライ'], image: '/pokemon-ierukana/assets/images/491Darkrai.png' },
  { id: 492, name: 'シェイミ', keyword: ['シェイミ'], image: '/pokemon-ierukana/assets/images/492Shaymin.png' },
  { id: 493, name: 'アルセウス', keyword: ['アルセウス'], image: '/pokemon-ierukana/assets/images/493Arceus.png' },
  { id: 494, name: 'ビクティニ', keyword: ['ビクティニ'], image: '/pokemon-ierukana/assets/images/494Victini.png' },
  { id: 495, name: 'ツタージャ', keyword: ['ツタージャ'], image: '/pokemon-ierukana/assets/images/495Snivy.png' },
  { id: 496, name: 'ジャノビー', keyword: ['ジャノビー'], image: '/pokemon-ierukana/assets/images/496Servine.png' },
  { id: 497, name: 'ジャローダ', keyword: ['ジャローダ'], image: '/pokemon-ierukana/assets/images/497Serperior.png' },
  { id: 498, name: 'ポカブ', keyword: ['ポカブ'], image: '/pokemon-ierukana/assets/images/498Tepig.png' },
  { id: 499, name: 'チャオブー', keyword: ['チャオブー'], image: '/pokemon-ierukana/assets/images/499Pignite.png' },
  { id: 500, name: 'エンブオー', keyword: ['エンブオー'], image: '/pokemon-ierukana/assets/images/500Emboar.png' },
  { id: 501, name: 'ミジュマル', keyword: ['ミジュマル'], image: '/pokemon-ierukana/assets/images/501Oshawott.png' },
  { id: 502, name: 'フタチマル', keyword: ['フタチマル'], image: '/pokemon-ierukana/assets/images/502Dewott.png' },
  { id: 503, name: 'ダイケンキ', keyword: ['ダイケンキ'], image: '/pokemon-ierukana/assets/images/503Samurott.png' },
  { id: 504, name: 'ミネズミ', keyword: ['ミネズミ'], image: '/pokemon-ierukana/assets/images/504Patrat.png' },
  { id: 505, name: 'ミルホッグ', keyword: ['ミルホッグ'], image: '/pokemon-ierukana/assets/images/505Watchog.png' },
  { id: 506, name: 'ヨーテリー', keyword: ['ヨーテリー'], image: '/pokemon-ierukana/assets/images/506Lillipup.png' },
  { id: 507, name: 'ハーデリア', keyword: ['ハーデリア'], image: '/pokemon-ierukana/assets/images/507Herdier.png' },
  { id: 508, name: 'ムーランド', keyword: ['ムーランド'], image: '/pokemon-ierukana/assets/images/508Stoutland.png' },
  { id: 509, name: 'チョロネコ', keyword: ['チョロネコ'], image: '/pokemon-ierukana/assets/images/509Purrloin.png' },
  { id: 510, name: 'レパルダス', keyword: ['レパルダス'], image: '/pokemon-ierukana/assets/images/510Liepard.png' },
  { id: 511, name: 'ヤナップ', keyword: ['ヤナップ'], image: '/pokemon-ierukana/assets/images/511Pansage.png' },
  { id: 512, name: 'ヤナッキー', keyword: ['ヤナッキー'], image: '/pokemon-ierukana/assets/images/512Simisage.png' },
  { id: 513, name: 'バオップ', keyword: ['バオップ'], image: '/pokemon-ierukana/assets/images/513Pansear.png' },
  { id: 514, name: 'バオッキー', keyword: ['バオッキー'], image: '/pokemon-ierukana/assets/images/514Simisear.png' },
  { id: 515, name: 'ヒヤップ', keyword: ['ヒヤップ'], image: '/pokemon-ierukana/assets/images/515Panpour.png' },
  { id: 516, name: 'ヒヤッキー', keyword: ['ヒヤッキー'], image: '/pokemon-ierukana/assets/images/516Simipour.png' },
  { id: 517, name: 'ムンナ', keyword: ['ムンナ'], image: '/pokemon-ierukana/assets/images/517Munna.png' },
  { id: 518, name: 'ムシャーナ', keyword: ['ムシャーナ'], image: '/pokemon-ierukana/assets/images/518Musharna.png' },
  { id: 519, name: 'マメパト', keyword: ['マメパト'], image: '/pokemon-ierukana/assets/images/519Pidove.png' },
  { id: 520, name: 'ハトーボー', keyword: ['ハトーボー'], image: '/pokemon-ierukana/assets/images/520Tranquill.png' },
  { id: 521, name: 'ケンホロウ', keyword: ['ケンホロウ'], image: '/pokemon-ierukana/assets/images/521Unfezant.png' },
  { id: 522, name: 'シママ', keyword: ['シママ'], image: '/pokemon-ierukana/assets/images/522Blitzle.png' },
  { id: 523, name: 'ゼブライカ', keyword: ['ゼブライカ'], image: '/pokemon-ierukana/assets/images/523Zebstrika.png' },
  { id: 524, name: 'ダンゴロ', keyword: ['ダンゴロ'], image: '/pokemon-ierukana/assets/images/524Roggenrola.png' },
  { id: 525, name: 'ガントル', keyword: ['ガントル'], image: '/pokemon-ierukana/assets/images/525Boldore.png' },
  { id: 526, name: 'ギガイアス', keyword: ['ギガイアス'], image: '/pokemon-ierukana/assets/images/526Gigalith.png' },
  { id: 527, name: 'コロモリ', keyword: ['コロモリ'], image: '/pokemon-ierukana/assets/images/527Woobat.png' },
  { id: 528, name: 'ココロモリ', keyword: ['ココロモリ'], image: '/pokemon-ierukana/assets/images/528Swoobat.png' },
  { id: 529, name: 'モグリュー', keyword: ['モグリュー'], image: '/pokemon-ierukana/assets/images/529Drilbur.png' },
  { id: 530, name: 'ドリュウズ', keyword: ['ドリュウズ'], image: '/pokemon-ierukana/assets/images/530Excadrill.png' },
  { id: 531, name: 'タブンネ', keyword: ['タブンネ'], image: '/pokemon-ierukana/assets/images/531Audino.png' },
  { id: 532, name: 'ドッコラー', keyword: ['ドッコラー'], image: '/pokemon-ierukana/assets/images/532Timburr.png' },
  { id: 533, name: 'ドテッコツ', keyword: ['ドテッコツ'], image: '/pokemon-ierukana/assets/images/533Gurdurr.png' },
  { id: 534, name: 'ローブシン', keyword: ['ローブシン'], image: '/pokemon-ierukana/assets/images/534Conkeldurr.png' },
  { id: 535, name: 'オタマロ', keyword: ['オタマロ'], image: '/pokemon-ierukana/assets/images/535Tympole.png' },
  { id: 536, name: 'ガマガル', keyword: ['ガマガル'], image: '/pokemon-ierukana/assets/images/536Palpitoad.png' },
  { id: 537, name: 'ガマゲロゲ', keyword: ['ガマゲロゲ'], image: '/pokemon-ierukana/assets/images/537Seismitoad.png' },
  { id: 538, name: 'ナゲキ', keyword: ['ナゲキ'], image: '/pokemon-ierukana/assets/images/538Throh.png' },
  { id: 539, name: 'ダゲキ', keyword: ['ダゲキ'], image: '/pokemon-ierukana/assets/images/539Sawk.png' },
  { id: 540, name: 'クルミル', keyword: ['クルミル'], image: '/pokemon-ierukana/assets/images/540Sewaddle.png' },
  { id: 541, name: 'クルマユ', keyword: ['クルマユ'], image: '/pokemon-ierukana/assets/images/541Swadloon.png' },
  { id: 542, name: 'ハハコモリ', keyword: ['ハハコモリ'], image: '/pokemon-ierukana/assets/images/542Leavanny.png' },
  { id: 543, name: 'フシデ', keyword: ['フシデ'], image: '/pokemon-ierukana/assets/images/543Venipede.png' },
  { id: 544, name: 'ホイーガ', keyword: ['ホイーガ'], image: '/pokemon-ierukana/assets/images/544Whirlipede.png' },
  { id: 545, name: 'ペンドラー', keyword: ['ペンドラー'], image: '/pokemon-ierukana/assets/images/545Scolipede.png' },
  { id: 546, name: 'モンメン', keyword: ['モンメン'], image: '/pokemon-ierukana/assets/images/546Cottonee.png' },
  { id: 547, name: 'エルフーン', keyword: ['エルフーン'], image: '/pokemon-ierukana/assets/images/547Whimsicott.png' },
  { id: 548, name: 'チュリネ', keyword: ['チュリネ'], image: '/pokemon-ierukana/assets/images/548Petilil.png' },
  { id: 549, name: 'ドレディア', keyword: ['ドレディア'], image: '/pokemon-ierukana/assets/images/549Lilligant.png' },
  { id: 550, name: 'バスラオ', keyword: ['バスラオ'], image: '/pokemon-ierukana/assets/images/550Basculin.png' },
  { id: 551, name: 'メグロコ', keyword: ['メグロコ'], image: '/pokemon-ierukana/assets/images/551Sandile.png' },
  { id: 552, name: 'ワルビル', keyword: ['ワルビル'], image: '/pokemon-ierukana/assets/images/552Krokorok.png' },
  { id: 553, name: 'ワルビアル', keyword: ['ワルビアル'], image: '/pokemon-ierukana/assets/images/553Krookodile.png' },
  { id: 554, name: 'ダルマッカ', keyword: ['ダルマッカ'], image: '/pokemon-ierukana/assets/images/554Darumaka.png' },
  { id: 555, name: 'ヒヒダルマ', keyword: ['ヒヒダルマ'], image: '/pokemon-ierukana/assets/images/555Darmanitan.png' },
  { id: 556, name: 'マラカッチ', keyword: ['マラカッチ'], image: '/pokemon-ierukana/assets/images/556Maractus.png' },
  { id: 557, name: 'イシズマイ', keyword: ['イシズマイ'], image: '/pokemon-ierukana/assets/images/557Dwebble.png' },
  { id: 558, name: 'イワパレス', keyword: ['イワパレス'], image: '/pokemon-ierukana/assets/images/558Crustle.png' },
  { id: 559, name: 'ズルッグ', keyword: ['ズルッグ'], image: '/pokemon-ierukana/assets/images/559Scraggy.png' },
  { id: 560, name: 'ズルズキン', keyword: ['ズルズキン'], image: '/pokemon-ierukana/assets/images/560Scrafty.png' },
  { id: 561, name: 'シンボラー', keyword: ['シンボラー'], image: '/pokemon-ierukana/assets/images/561Sigilyph.png' },
  { id: 562, name: 'デスマス', keyword: ['デスマス'], image: '/pokemon-ierukana/assets/images/562Yamask.png' },
  { id: 563, name: 'デスカーン', keyword: ['デスカーン'], image: '/pokemon-ierukana/assets/images/563Cofagrigus.png' },
  { id: 564, name: 'プロトーガ', keyword: ['プロトーガ'], image: '/pokemon-ierukana/assets/images/564Tirtouga.png' },
  { id: 565, name: 'アバゴーラ', keyword: ['アバゴーラ'], image: '/pokemon-ierukana/assets/images/565Carracosta.png' },
  { id: 566, name: 'アーケン', keyword: ['アーケン'], image: '/pokemon-ierukana/assets/images/566Archen.png' },
  { id: 567, name: 'アーケオス', keyword: ['アーケオス'], image: '/pokemon-ierukana/assets/images/567Archeops.png' },
  { id: 568, name: 'ヤブクロン', keyword: ['ヤブクロン'], image: '/pokemon-ierukana/assets/images/568Trubbish.png' },
  { id: 569, name: 'ダストダス', keyword: ['ダストダス'], image: '/pokemon-ierukana/assets/images/569Garbodor.png' },
  { id: 570, name: 'ゾロア', keyword: ['ゾロア'], image: '/pokemon-ierukana/assets/images/570Zorua.png' },
  { id: 571, name: 'ゾロアーク', keyword: ['ゾロアーク'], image: '/pokemon-ierukana/assets/images/571Zoroark.png' },
  { id: 572, name: 'チラーミィ', keyword: ['チラーミィ'], image: '/pokemon-ierukana/assets/images/572Minccino.png' },
  { id: 573, name: 'チラチーノ', keyword: ['チラチーノ'], image: '/pokemon-ierukana/assets/images/573Cinccino.png' },
  { id: 574, name: 'ゴチム', keyword: ['ゴチム'], image: '/pokemon-ierukana/assets/images/574Gothita.png' },
  { id: 575, name: 'ゴチミル', keyword: ['ゴチミル'], image: '/pokemon-ierukana/assets/images/575Gothorita.png' },
  { id: 576, name: 'ゴチルゼル', keyword: ['ゴチルゼル'], image: '/pokemon-ierukana/assets/images/576Gothitelle.png' },
  { id: 577, name: 'ユニラン', keyword: ['ユニラン'], image: '/pokemon-ierukana/assets/images/577Solosis.png' },
  { id: 578, name: 'ダブラン', keyword: ['ダブラン'], image: '/pokemon-ierukana/assets/images/578Duosion.png' },
  { id: 579, name: 'ランクルス', keyword: ['ランクルス'], image: '/pokemon-ierukana/assets/images/579Reuniclus.png' },
  { id: 580, name: 'コアルヒー', keyword: ['コアルヒー'], image: '/pokemon-ierukana/assets/images/580Ducklett.png' },
  { id: 581, name: 'スワンナ', keyword: ['スワンナ'], image: '/pokemon-ierukana/assets/images/581Swanna.png' },
  { id: 582, name: 'バニプッチ', keyword: ['バニプッチ'], image: '/pokemon-ierukana/assets/images/582Vanillite.png' },
  { id: 583, name: 'バニリッチ', keyword: ['バニリッチ'], image: '/pokemon-ierukana/assets/images/583Vanillish.png' },
  { id: 584, name: 'バイバニラ', keyword: ['バイバニラ'], image: '/pokemon-ierukana/assets/images/584Vanilluxe.png' },
  { id: 585, name: 'シキジカ', keyword: ['シキジカ'], image: '/pokemon-ierukana/assets/images/585Deerling.png' },
  { id: 586, name: 'メブキジカ', keyword: ['メブキジカ'], image: '/pokemon-ierukana/assets/images/586Sawsbuck.png' },
  { id: 587, name: 'エモンガ', keyword: ['エモンガ'], image: '/pokemon-ierukana/assets/images/587Emolga.png' },
  { id: 588, name: 'カブルモ', keyword: ['カブルモ'], image: '/pokemon-ierukana/assets/images/588Karrablast.png' },
  { id: 589, name: 'シュバルゴ', keyword: ['シュバルゴ'], image: '/pokemon-ierukana/assets/images/589Escavalier.png' },
  { id: 590, name: 'タマゲタケ', keyword: ['タマゲタケ'], image: '/pokemon-ierukana/assets/images/590Foongus.png' },
  { id: 591, name: 'モロバレル', keyword: ['モロバレル'], image: '/pokemon-ierukana/assets/images/591Amoonguss.png' },
  { id: 592, name: 'プルリル', keyword: ['プルリル'], image: '/pokemon-ierukana/assets/images/592Frillish.png' },
  { id: 593, name: 'ブルンゲル', keyword: ['ブルンゲル'], image: '/pokemon-ierukana/assets/images/593Jellicent.png' },
  { id: 594, name: 'ママンボウ', keyword: ['ママンボウ'], image: '/pokemon-ierukana/assets/images/594Alomomola.png' },
  { id: 595, name: 'バチュル', keyword: ['バチュル'], image: '/pokemon-ierukana/assets/images/595Joltik.png' },
  { id: 596, name: 'デンチュラ', keyword: ['デンチュラ'], image: '/pokemon-ierukana/assets/images/596Galvantula.png' },
  { id: 597, name: 'テッシード', keyword: ['テッシード'], image: '/pokemon-ierukana/assets/images/597Ferroseed.png' },
  { id: 598, name: 'ナットレイ', keyword: ['ナットレイ'], image: '/pokemon-ierukana/assets/images/598Ferrothorn.png' },
  { id: 599, name: 'ギアル', keyword: ['ギアル'], image: '/pokemon-ierukana/assets/images/599Klink.png' },
  { id: 600, name: 'ギギアル', keyword: ['ギギアル'], image: '/pokemon-ierukana/assets/images/600Klang.png' },
  { id: 601, name: 'ギギギアル', keyword: ['ギギギアル'], image: '/pokemon-ierukana/assets/images/601Klinklang.png' },
  { id: 602, name: 'シビシラス', keyword: ['シビシラス'], image: '/pokemon-ierukana/assets/images/602Tynamo.png' },
  { id: 603, name: 'シビビール', keyword: ['シビビール'], image: '/pokemon-ierukana/assets/images/603Eelektrik.png' },
  { id: 604, name: 'シビルドン', keyword: ['シビルドン'], image: '/pokemon-ierukana/assets/images/604Eelektross.png' },
  { id: 605, name: 'リグレー', keyword: ['リグレー'], image: '/pokemon-ierukana/assets/images/605Elgyem.png' },
  { id: 606, name: 'オーベム', keyword: ['オーベム'], image: '/pokemon-ierukana/assets/images/606Beheeyem.png' },
  { id: 607, name: 'ヒトモシ', keyword: ['ヒトモシ'], image: '/pokemon-ierukana/assets/images/607Litwick.png' },
  { id: 608, name: 'ランプラー', keyword: ['ランプラー'], image: '/pokemon-ierukana/assets/images/608Lampent.png' },
  { id: 609, name: 'シャンデラ', keyword: ['シャンデラ'], image: '/pokemon-ierukana/assets/images/609Chandelure.png' },
  { id: 610, name: 'キバゴ', keyword: ['キバゴ'], image: '/pokemon-ierukana/assets/images/610Axew.png' },
  { id: 611, name: 'オノンド', keyword: ['オノンド'], image: '/pokemon-ierukana/assets/images/611Fraxure.png' },
  { id: 612, name: 'オノノクス', keyword: ['オノノクス'], image: '/pokemon-ierukana/assets/images/612Haxorus.png' },
  { id: 613, name: 'クマシュン', keyword: ['クマシュン'], image: '/pokemon-ierukana/assets/images/613Cubchoo.png' },
  { id: 614, name: 'ツンベアー', keyword: ['ツンベアー'], image: '/pokemon-ierukana/assets/images/614Beartic.png' },
  { id: 615, name: 'フリージオ', keyword: ['フリージオ'], image: '/pokemon-ierukana/assets/images/615Cryogonal.png' },
  { id: 616, name: 'チョボマキ', keyword: ['チョボマキ'], image: '/pokemon-ierukana/assets/images/616Shelmet.png' },
  { id: 617, name: 'アギルダー', keyword: ['アギルダー'], image: '/pokemon-ierukana/assets/images/617Accelgor.png' },
  { id: 618, name: 'マッギョ', keyword: ['マッギョ'], image: '/pokemon-ierukana/assets/images/618Stunfisk.png' },
  { id: 619, name: 'コジョフー', keyword: ['コジョフー'], image: '/pokemon-ierukana/assets/images/619Mienfoo.png' },
  { id: 620, name: 'コジョンド', keyword: ['コジョンド'], image: '/pokemon-ierukana/assets/images/620Mienshao.png' },
  { id: 621, name: 'クリムガン', keyword: ['クリムガン'], image: '/pokemon-ierukana/assets/images/621Druddigon.png' },
  { id: 622, name: 'ゴビット', keyword: ['ゴビット'], image: '/pokemon-ierukana/assets/images/622Golett.png' },
  { id: 623, name: 'ゴルーグ', keyword: ['ゴルーグ'], image: '/pokemon-ierukana/assets/images/623Golurk.png' },
  { id: 624, name: 'コマタナ', keyword: ['コマタナ'], image: '/pokemon-ierukana/assets/images/624Pawniard.png' },
  { id: 625, name: 'キリキザン', keyword: ['キリキザン'], image: '/pokemon-ierukana/assets/images/625Bisharp.png' },
  { id: 626, name: 'バッフロン', keyword: ['バッフロン'], image: '/pokemon-ierukana/assets/images/626Bouffalant.png' },
  { id: 627, name: 'ワシボン', keyword: ['ワシボン'], image: '/pokemon-ierukana/assets/images/627Rufflet.png' },
  { id: 628, name: 'ウォーグル', keyword: ['ウォーグル'], image: '/pokemon-ierukana/assets/images/628Braviary.png' },
  { id: 629, name: 'バルチャイ', keyword: ['バルチャイ'], image: '/pokemon-ierukana/assets/images/629Vullaby.png' },
  { id: 630, name: 'バルジーナ', keyword: ['バルジーナ'], image: '/pokemon-ierukana/assets/images/630Mandibuzz.png' },
  { id: 631, name: 'クイタラン', keyword: ['クイタラン'], image: '/pokemon-ierukana/assets/images/631Heatmor.png' },
  { id: 632, name: 'アイアント', keyword: ['アイアント'], image: '/pokemon-ierukana/assets/images/632Durant.png' },
  { id: 633, name: 'モノズ', keyword: ['モノズ'], image: '/pokemon-ierukana/assets/images/633Deino.png' },
  { id: 634, name: 'ジヘッド', keyword: ['ジヘッド'], image: '/pokemon-ierukana/assets/images/634Zweilous.png' },
  { id: 635, name: 'サザンドラ', keyword: ['サザンドラ'], image: '/pokemon-ierukana/assets/images/635Hydreigon.png' },
  { id: 636, name: 'メラルバ', keyword: ['メラルバ'], image: '/pokemon-ierukana/assets/images/636Larvesta.png' },
  { id: 637, name: 'ウルガモス', keyword: ['ウルガモス'], image: '/pokemon-ierukana/assets/images/637Volcarona.png' },
  { id: 638, name: 'コバルオン', keyword: ['コバルオン'], image: '/pokemon-ierukana/assets/images/638Cobalion.png' },
  { id: 639, name: 'テラキオン', keyword: ['テラキオン'], image: '/pokemon-ierukana/assets/images/639Terrakion.png' },
  { id: 640, name: 'ビリジオン', keyword: ['ビリジオン'], image: '/pokemon-ierukana/assets/images/640Virizion.png' },
  { id: 641, name: 'トルネロス', keyword: ['トルネロス'], image: '/pokemon-ierukana/assets/images/641Tornadus.png' },
  { id: 642, name: 'ボルトロス', keyword: ['ボルトロス'], image: '/pokemon-ierukana/assets/images/642Thundurus.png' },
  { id: 643, name: 'レシラム', keyword: ['レシラム'], image: '/pokemon-ierukana/assets/images/643Reshiram.png' },
  { id: 644, name: 'ゼクロム', keyword: ['ゼクロム'], image: '/pokemon-ierukana/assets/images/644Zekrom.png' },
  { id: 645, name: 'ランドロス', keyword: ['ランドロス'], image: '/pokemon-ierukana/assets/images/645Landorus.png' },
  { id: 646, name: 'キュレム', keyword: ['キュレム'], image: '/pokemon-ierukana/assets/images/646Kyurem.png' },
  { id: 647, name: 'ケルディオ', keyword: ['ケルディオ'], image: '/pokemon-ierukana/assets/images/647Keldeo.png' },
  { id: 648, name: 'メロエッタ', keyword: ['メロエッタ'], image: '/pokemon-ierukana/assets/images/648Meloetta.png' },
  { id: 649, name: 'ゲノセクト', keyword: ['ゲノセクト'], image: '/pokemon-ierukana/assets/images/649Genesect.png' },
  { id: 650, name: 'ハリマロン', keyword: ['ハリマロン'], image: '/pokemon-ierukana/assets/images/650Chespin.png' },
  { id: 651, name: 'ハリボーグ', keyword: ['ハリボーグ'], image: '/pokemon-ierukana/assets/images/651Quilladin.png' },
  { id: 652, name: 'ブリガロン', keyword: ['ブリガロン'], image: '/pokemon-ierukana/assets/images/652Chesnaught.png' },
  { id: 653, name: 'フォッコ', keyword: ['フォッコ'], image: '/pokemon-ierukana/assets/images/653Fennekin.png' },
  { id: 654, name: 'テールナー', keyword: ['テールナー'], image: '/pokemon-ierukana/assets/images/654Braixen.png' },
  { id: 655, name: 'マフォクシー', keyword: ['マフォクシー'], image: '/pokemon-ierukana/assets/images/655Delphox.png' },
  { id: 656, name: 'ケロマツ', keyword: ['ケロマツ'], image: '/pokemon-ierukana/assets/images/656Froakie.png' },
  { id: 657, name: 'ゲコガシラ', keyword: ['ゲコガシラ'], image: '/pokemon-ierukana/assets/images/657Frogadier.png' },
  { id: 658, name: 'ゲッコウガ', keyword: ['ゲッコウガ'], image: '/pokemon-ierukana/assets/images/658Greninja.png' },
  { id: 659, name: 'ホルビー', keyword: ['ホルビー'], image: '/pokemon-ierukana/assets/images/659Bunnelby.png' },
  { id: 660, name: 'ホルード', keyword: ['ホルード'], image: '/pokemon-ierukana/assets/images/660Diggersby.png' },
  { id: 661, name: 'ヤヤコマ', keyword: ['ヤヤコマ'], image: '/pokemon-ierukana/assets/images/661Fletchling.png' },
  { id: 662, name: 'ヒノヤコマ', keyword: ['ヒノヤコマ'], image: '/pokemon-ierukana/assets/images/662Fletchinder.png' },
  { id: 663, name: 'ファイアロー', keyword: ['ファイアロー'], image: '/pokemon-ierukana/assets/images/663Talonflame.png' },
  { id: 664, name: 'コフキムシ', keyword: ['コフキムシ'], image: '/pokemon-ierukana/assets/images/664Scatterbug.png' },
  { id: 665, name: 'コフーライ', keyword: ['コフーライ'], image: '/pokemon-ierukana/assets/images/665Spewpa.png' },
  { id: 666, name: 'ビビヨン', keyword: ['ビビヨン'], image: '/pokemon-ierukana/assets/images/666Vivillon.png' },
  { id: 667, name: 'シシコ', keyword: ['シシコ'], image: '/pokemon-ierukana/assets/images/667Litleo.png' },
  { id: 668, name: 'カエンジシ', keyword: ['カエンジシ'], image: '/pokemon-ierukana/assets/images/668Pyroar.png' },
  { id: 669, name: 'フラベベ', keyword: ['フラベベ'], image: '/pokemon-ierukana/assets/images/669Flabebe.png' },
  { id: 670, name: 'フラエッテ', keyword: ['フラエッテ'], image: '/pokemon-ierukana/assets/images/670Floette.png' },
  { id: 671, name: 'フラージェス', keyword: ['フラージェス'], image: '/pokemon-ierukana/assets/images/671Florges.png' },
  { id: 672, name: 'メェークル', keyword: ['メェークル'], image: '/pokemon-ierukana/assets/images/672Skiddo.png' },
  { id: 673, name: 'ゴーゴート', keyword: ['ゴーゴート'], image: '/pokemon-ierukana/assets/images/673Gogoat.png' },
  { id: 674, name: 'ヤンチャム', keyword: ['ヤンチャム'], image: '/pokemon-ierukana/assets/images/674Pancham.png' },
  { id: 675, name: 'ゴロンダ', keyword: ['ゴロンダ'], image: '/pokemon-ierukana/assets/images/675Pangoro.png' },
  { id: 676, name: 'トリミアン', keyword: ['トリミアン'], image: '/pokemon-ierukana/assets/images/676Furfrou.png' },
  { id: 677, name: 'ニャスパー', keyword: ['ニャスパー'], image: '/pokemon-ierukana/assets/images/677Espurr.png' },
  { id: 678, name: 'ニャオニクス', keyword: ['ニャオニクス'], image: '/pokemon-ierukana/assets/images/678Meowstic.png' },
  { id: 679, name: 'ヒトツキ', keyword: ['ヒトツキ'], image: '/pokemon-ierukana/assets/images/679Honedge.png' },
  { id: 680, name: 'ニダンギル', keyword: ['ニダンギル'], image: '/pokemon-ierukana/assets/images/680Doublade.png' },
  { id: 681, name: 'ギルガルド', keyword: ['ギルガルド'], image: '/pokemon-ierukana/assets/images/681Aegislash.png' },
  { id: 682, name: 'シュシュプ', keyword: ['シュシュプ'], image: '/pokemon-ierukana/assets/images/682Spritzee.png' },
  { id: 683, name: 'フレフワン', keyword: ['フレフワン'], image: '/pokemon-ierukana/assets/images/683Aromatisse.png' },
  { id: 684, name: 'ペロッパフ', keyword: ['ペロッパフ'], image: '/pokemon-ierukana/assets/images/684Swirlix.png' },
  { id: 685, name: 'ペロリーム', keyword: ['ペロリーム'], image: '/pokemon-ierukana/assets/images/685Slurpuff.png' },
  { id: 686, name: 'マーイーカ', keyword: ['マーイーカ'], image: '/pokemon-ierukana/assets/images/686Inkay.png' },
  { id: 687, name: 'カラマネロ', keyword: ['カラマネロ'], image: '/pokemon-ierukana/assets/images/687Malamar.png' },
  { id: 688, name: 'カメテテ', keyword: ['カメテテ'], image: '/pokemon-ierukana/assets/images/688Binacle.png' },
  { id: 689, name: 'ガメノデス', keyword: ['ガメノデス'], image: '/pokemon-ierukana/assets/images/689Barbaracle.png' },
  { id: 690, name: 'クズモー', keyword: ['クズモー'], image: '/pokemon-ierukana/assets/images/690Skrelp.png' },
  { id: 691, name: 'ドラミドロ', keyword: ['ドラミドロ'], image: '/pokemon-ierukana/assets/images/691Dragalge.png' },
  { id: 692, name: 'ウデッポウ', keyword: ['ウデッポウ'], image: '/pokemon-ierukana/assets/images/692Clauncher.png' },
  { id: 693, name: 'ブロスター', keyword: ['ブロスター'], image: '/pokemon-ierukana/assets/images/693Clawitzer.png' },
  { id: 694, name: 'エリキテル', keyword: ['エリキテル'], image: '/pokemon-ierukana/assets/images/694Helioptile.png' },
  { id: 695, name: 'エレザード', keyword: ['エレザード'], image: '/pokemon-ierukana/assets/images/695Heliolisk.png' },
  { id: 696, name: 'チゴラス', keyword: ['チゴラス'], image: '/pokemon-ierukana/assets/images/696Tyrunt.png' },
  { id: 697, name: 'ガチゴラス', keyword: ['ガチゴラス'], image: '/pokemon-ierukana/assets/images/697Tyrantrum.png' },
  { id: 698, name: 'アマルス', keyword: ['アマルス'], image: '/pokemon-ierukana/assets/images/698Amaura.png' },
  { id: 699, name: 'アマルルガ', keyword: ['アマルルガ'], image: '/pokemon-ierukana/assets/images/699Aurorus.png' },
  { id: 700, name: 'ニンフィア', keyword: ['ニンフィア'], image: '/pokemon-ierukana/assets/images/700Sylveon.png' },
  { id: 701, name: 'ルチャブル', keyword: ['ルチャブル'], image: '/pokemon-ierukana/assets/images/701Hawlucha.png' },
  { id: 702, name: 'デデンネ', keyword: ['デデンネ'], image: '/pokemon-ierukana/assets/images/702Dedenne.png' },
  { id: 703, name: 'メレシー', keyword: ['メレシー'], image: '/pokemon-ierukana/assets/images/703Carbink.png' },
  { id: 704, name: 'ヌメラ', keyword: ['ヌメラ'], image: '/pokemon-ierukana/assets/images/704Goomy.png' },
  { id: 705, name: 'ヌメイル', keyword: ['ヌメイル'], image: '/pokemon-ierukana/assets/images/705Sliggoo.png' },
  { id: 706, name: 'ヌメルゴン', keyword: ['ヌメルゴン'], image: '/pokemon-ierukana/assets/images/706Goodra.png' },
  { id: 707, name: 'クレッフィ', keyword: ['クレッフィ'], image: '/pokemon-ierukana/assets/images/707Klefki.png' },
  { id: 708, name: 'ボクレー', keyword: ['ボクレー'], image: '/pokemon-ierukana/assets/images/708Phantump.png' },
  { id: 709, name: 'オーロット', keyword: ['オーロット'], image: '/pokemon-ierukana/assets/images/709Trevenant.png' },
  { id: 710, name: 'バケッチャ', keyword: ['バケッチャ'], image: '/pokemon-ierukana/assets/images/710Pumpkaboo.png' },
  { id: 711, name: 'パンプジン', keyword: ['パンプジン'], image: '/pokemon-ierukana/assets/images/711Gourgeist.png' },
  { id: 712, name: 'カチコール', keyword: ['カチコール'], image: '/pokemon-ierukana/assets/images/712Bergmite.png' },
  { id: 713, name: 'クレベース', keyword: ['クレベース'], image: '/pokemon-ierukana/assets/images/713Avalugg.png' },
  { id: 714, name: 'オンバット', keyword: ['オンバット'], image: '/pokemon-ierukana/assets/images/714Noibat.png' },
  { id: 715, name: 'オンバーン', keyword: ['オンバーン'], image: '/pokemon-ierukana/assets/images/715Noivern.png' },
  { id: 716, name: 'ゼルネアス', keyword: ['ゼルネアス'], image: '/pokemon-ierukana/assets/images/716Xerneas.png' },
  { id: 717, name: 'イベルタル', keyword: ['イベルタル'], image: '/pokemon-ierukana/assets/images/717Yveltal.png' },
  { id: 718, name: 'ジガルデ', keyword: ['ジガルデ'], image: '/pokemon-ierukana/assets/images/718Zygarde.png' },
  { id: 719, name: 'ディアンシー', keyword: ['ディアンシー'], image: '/pokemon-ierukana/assets/images/719Diancie.png' },
  { id: 720, name: 'フーパ', keyword: ['フーパ'], image: '/pokemon-ierukana/assets/images/720Hoopa.png' },
  { id: 721, name: 'ボルケニオン', keyword: ['ボルケニオン'], image: '/pokemon-ierukana/assets/images/721Volcanion.png' },
  { id: 722, name: 'モクロー', keyword: ['モクロー'], image: '/pokemon-ierukana/assets/images/722Rowlet.png' },
  { id: 723, name: 'フクスロー', keyword: ['フクスロー'], image: '/pokemon-ierukana/assets/images/723Dartrix.png' },
  { id: 724, name: 'ジュナイパー', keyword: ['ジュナイパー'], image: '/pokemon-ierukana/assets/images/724Decidueye.png' },
  { id: 725, name: 'ニャビー', keyword: ['ニャビー'], image: '/pokemon-ierukana/assets/images/725Litten.png' },
  { id: 726, name: 'ニャヒート', keyword: ['ニャヒート'], image: '/pokemon-ierukana/assets/images/726Torracat.png' },
  { id: 727, name: 'ガオガエン', keyword: ['ガオガエン'], image: '/pokemon-ierukana/assets/images/727Incineroar.png' },
  { id: 728, name: 'アシマリ', keyword: ['アシマリ'], image: '/pokemon-ierukana/assets/images/728Popplio.png' },
  { id: 729, name: 'オシャマリ', keyword: ['オシャマリ'], image: '/pokemon-ierukana/assets/images/729Brionne.png' },
  { id: 730, name: 'アシレーヌ', keyword: ['アシレーヌ'], image: '/pokemon-ierukana/assets/images/730Primarina.png' },
  { id: 731, name: 'ツツケラ', keyword: ['ツツケラ'], image: '/pokemon-ierukana/assets/images/731Pikipek.png' },
  { id: 732, name: 'ケララッパ', keyword: ['ケララッパ'], image: '/pokemon-ierukana/assets/images/732Trumbeak.png' },
  { id: 733, name: 'ドデカバシ', keyword: ['ドデカバシ'], image: '/pokemon-ierukana/assets/images/733Toucannon.png' },
  { id: 734, name: 'ヤングース', keyword: ['ヤングース'], image: '/pokemon-ierukana/assets/images/734Yungoos.png' },
  { id: 735, name: 'デカグース', keyword: ['デカグース'], image: '/pokemon-ierukana/assets/images/735Gumshoos.png' },
  { id: 736, name: 'アゴジムシ', keyword: ['アゴジムシ'], image: '/pokemon-ierukana/assets/images/736Grubbin.png' },
  { id: 737, name: 'デンヂムシ', keyword: ['デンヂムシ'], image: '/pokemon-ierukana/assets/images/737Charjabug.png' },
  { id: 738, name: 'クワガノン', keyword: ['クワガノン'], image: '/pokemon-ierukana/assets/images/738Vikavolt.png' },
  { id: 739, name: 'マケンカニ', keyword: ['マケンカニ'], image: '/pokemon-ierukana/assets/images/739Crabrawler.png' },
  { id: 740, name: 'ケケンカニ', keyword: ['ケケンカニ'], image: '/pokemon-ierukana/assets/images/740Crabominable.png' },
  { id: 741, name: 'オドリドリ', keyword: ['オドリドリ'], image: '/pokemon-ierukana/assets/images/741Oricorio.png' },
  { id: 742, name: 'アブリー', keyword: ['アブリー'], image: '/pokemon-ierukana/assets/images/742Cutiefly.png' },
  { id: 743, name: 'アブリボン', keyword: ['アブリボン'], image: '/pokemon-ierukana/assets/images/743Ribombee.png' },
  { id: 744, name: 'イワンコ', keyword: ['イワンコ'], image: '/pokemon-ierukana/assets/images/744Rockruff.png' },
  { id: 745, name: 'ルガルガン', keyword: ['ルガルガン'], image: '/pokemon-ierukana/assets/images/745Lycanroc.png' },
  { id: 746, name: 'ヨワシ', keyword: ['ヨワシ'], image: '/pokemon-ierukana/assets/images/746Wishiwashi.png' },
  { id: 747, name: 'ヒドイデ', keyword: ['ヒドイデ'], image: '/pokemon-ierukana/assets/images/747Mareanie.png' },
  { id: 748, name: 'ドヒドイデ', keyword: ['ドヒドイデ'], image: '/pokemon-ierukana/assets/images/748Toxapex.png' },
  { id: 749, name: 'ドロバンコ', keyword: ['ドロバンコ'], image: '/pokemon-ierukana/assets/images/749Mudbray.png' },
  { id: 750, name: 'バンバドロ', keyword: ['バンバドロ'], image: '/pokemon-ierukana/assets/images/750Mudsdale.png' },
  { id: 751, name: 'シズクモ', keyword: ['シズクモ'], image: '/pokemon-ierukana/assets/images/751Dewpider.png' },
  { id: 752, name: 'オニシズクモ', keyword: ['オニシズクモ'], image: '/pokemon-ierukana/assets/images/752Araquanid.png' },
  { id: 753, name: 'カリキリ', keyword: ['カリキリ'], image: '/pokemon-ierukana/assets/images/753Fomantis.png' },
  { id: 754, name: 'ラランテス', keyword: ['ラランテス'], image: '/pokemon-ierukana/assets/images/754Lurantis.png' },
  { id: 755, name: 'ネマシュ', keyword: ['ネマシュ'], image: '/pokemon-ierukana/assets/images/755Morelull.png' },
  { id: 756, name: 'マシェード', keyword: ['マシェード'], image: '/pokemon-ierukana/assets/images/756Shiinotic.png' },
  { id: 757, name: 'ヤトウモリ', keyword: ['ヤトウモリ'], image: '/pokemon-ierukana/assets/images/757Salandit.png' },
  { id: 758, name: 'エンニュート', keyword: ['エンニュート'], image: '/pokemon-ierukana/assets/images/758Salazzle.png' },
  { id: 759, name: 'ヌイコグマ', keyword: ['ヌイコグマ'], image: '/pokemon-ierukana/assets/images/759Stufful.png' },
  { id: 760, name: 'キテルグマ', keyword: ['キテルグマ'], image: '/pokemon-ierukana/assets/images/760Bewear.png' },
  { id: 761, name: 'アマカジ', keyword: ['アマカジ'], image: '/pokemon-ierukana/assets/images/761Bounsweet.png' },
  { id: 762, name: 'アママイコ', keyword: ['アママイコ'], image: '/pokemon-ierukana/assets/images/762Steenee.png' },
  { id: 763, name: 'アマージョ', keyword: ['アマージョ'], image: '/pokemon-ierukana/assets/images/763Tsareena.png' },
  { id: 764, name: 'キュワワー', keyword: ['キュワワー'], image: '/pokemon-ierukana/assets/images/764Comfey.png' },
  { id: 765, name: 'ヤレユータン', keyword: ['ヤレユータン'], image: '/pokemon-ierukana/assets/images/765Oranguru.png' },
  { id: 766, name: 'ナゲツケサル', keyword: ['ナゲツケサル'], image: '/pokemon-ierukana/assets/images/766Passimian.png' },
  { id: 767, name: 'コソクムシ', keyword: ['コソクムシ'], image: '/pokemon-ierukana/assets/images/767Wimpod.png' },
  { id: 768, name: 'グソクムシャ', keyword: ['グソクムシャ'], image: '/pokemon-ierukana/assets/images/768Golisopod.png' },
  { id: 769, name: 'スナバァ', keyword: ['スナバァ'], image: '/pokemon-ierukana/assets/images/769Sandygast.png' },
  { id: 770, name: 'シロデスナ', keyword: ['シロデスナ'], image: '/pokemon-ierukana/assets/images/770Palossand.png' },
  { id: 771, name: 'ナマコブシ', keyword: ['ナマコブシ'], image: '/pokemon-ierukana/assets/images/771Pyukumuku.png' },
  {
    id: 772,
    name: 'タイプ：ヌル',
    keyword: ['タイプ：ヌル', 'タイプ:ヌル', 'タイプヌル'],
    image: '/pokemon-ierukana/assets/images/772Type_Null.png'
  },
  { id: 773, name: 'シルヴァディ', keyword: ['シルヴァディ'], image: '/pokemon-ierukana/assets/images/773Silvally.png' },
  { id: 774, name: 'メテノ', keyword: ['メテノ'], image: '/pokemon-ierukana/assets/images/774Minior.png' },
  { id: 775, name: 'ネッコアラ', keyword: ['ネッコアラ'], image: '/pokemon-ierukana/assets/images/775Komala.png' },
  { id: 776, name: 'バクガメス', keyword: ['バクガメス'], image: '/pokemon-ierukana/assets/images/776Turtonator.png' },
  { id: 777, name: 'トゲデマル', keyword: ['トゲデマル'], image: '/pokemon-ierukana/assets/images/777Togedemaru.png' },
  { id: 778, name: 'ミミッキュ', keyword: ['ミミッキュ'], image: '/pokemon-ierukana/assets/images/778Mimikyu.png' },
  { id: 779, name: 'ハギギシリ', keyword: ['ハギギシリ'], image: '/pokemon-ierukana/assets/images/779Bruxish.png' },
  { id: 780, name: 'ジジーロン', keyword: ['ジジーロン'], image: '/pokemon-ierukana/assets/images/780Drampa.png' },
  { id: 781, name: 'ダダリン', keyword: ['ダダリン'], image: '/pokemon-ierukana/assets/images/781Dhelmise.png' },
  { id: 782, name: 'ジャラコ', keyword: ['ジャラコ'], image: '/pokemon-ierukana/assets/images/782Jangmo-o.png' },
  { id: 783, name: 'ジャランゴ', keyword: ['ジャランゴ'], image: '/pokemon-ierukana/assets/images/783Hakamo-o.png' },
  { id: 784, name: 'ジャラランガ', keyword: ['ジャラランガ'], image: '/pokemon-ierukana/assets/images/784Kommo-o.png' },
  { id: 785, name: 'カプ・コケコ', keyword: ['カプ・コケコ', 'カプコケコ'], image: '/pokemon-ierukana/assets/images/785Tapu_Koko.png' },
  { id: 786, name: 'カプ・テテフ', keyword: ['カプ・テテフ', 'カプテテフ'], image: '/pokemon-ierukana/assets/images/786Tapu_Lele.png' },
  { id: 787, name: 'カプ・ブルル', keyword: ['カプ・ブルル', 'カプブルル'], image: '/pokemon-ierukana/assets/images/787Tapu_Bulu.png' },
  { id: 788, name: 'カプ・レヒレ', keyword: ['カプ・レヒレ', 'カプレヒレ'], image: '/pokemon-ierukana/assets/images/788Tapu_Fini.png' },
  { id: 789, name: 'コスモッグ', keyword: ['コスモッグ'], image: '/pokemon-ierukana/assets/images/789Cosmog.png' },
  { id: 790, name: 'コスモウム', keyword: ['コスモウム'], image: '/pokemon-ierukana/assets/images/790Cosmoem.png' },
  { id: 791, name: 'ソルガレオ', keyword: ['ソルガレオ'], image: '/pokemon-ierukana/assets/images/791Solgaleo.png' },
  { id: 792, name: 'ルナアーラ', keyword: ['ルナアーラ'], image: '/pokemon-ierukana/assets/images/792Lunala.png' },
  { id: 793, name: 'ウツロイド', keyword: ['ウツロイド'], image: '/pokemon-ierukana/assets/images/793Nihilego.png' },
  { id: 794, name: 'マッシブーン', keyword: ['マッシブーン'], image: '/pokemon-ierukana/assets/images/794Buzzwole.png' },
  { id: 795, name: 'フェローチェ', keyword: ['フェローチェ'], image: '/pokemon-ierukana/assets/images/795Pheromosa.png' },
  { id: 796, name: 'デンジュモク', keyword: ['デンジュモク'], image: '/pokemon-ierukana/assets/images/796Xurkitree.png' },
  { id: 797, name: 'テッカグヤ', keyword: ['テッカグヤ'], image: '/pokemon-ierukana/assets/images/797Celesteela.png' },
  { id: 798, name: 'カミツルギ', keyword: ['カミツルギ'], image: '/pokemon-ierukana/assets/images/798Kartana.png' },
  { id: 799, name: 'アクジキング', keyword: ['アクジキング'], image: '/pokemon-ierukana/assets/images/799Guzzlord.png' },
  { id: 800, name: 'ネクロズマ', keyword: ['ネクロズマ'], image: '/pokemon-ierukana/assets/images/800Necrozma.png' },
  { id: 801, name: 'マギアナ', keyword: ['マギアナ'], image: '/pokemon-ierukana/assets/images/801Magearna.png' },
  { id: 802, name: 'マーシャドー', keyword: ['マーシャドー'], image: '/pokemon-ierukana/assets/images/802Marshadow.png' },
  { id: 803, name: 'ベベノム', keyword: ['ベベノム'], image: '/pokemon-ierukana/assets/images/803Poipole.png' },
  { id: 804, name: 'アーゴヨン', keyword: ['アーゴヨン'], image: '/pokemon-ierukana/assets/images/804Naganadel.png' },
  { id: 805, name: 'ツンデツンデ', keyword: ['ツンデツンデ'], image: '/pokemon-ierukana/assets/images/805Stakataka.png' },
  { id: 806, name: 'ズガドーン', keyword: ['ズガドーン'], image: '/pokemon-ierukana/assets/images/806Blacephalon.png' },
  { id: 807, name: 'ゼラオラ', keyword: ['ゼラオラ'], image: '/pokemon-ierukana/assets/images/807Zeraora.png' },
  { id: 808, name: 'メルタン', keyword: ['メルタン'], image: '/pokemon-ierukana/assets/images/808Meltan.png' },
  { id: 809, name: 'メルメタル', keyword: ['メルメタル'], image: '/pokemon-ierukana/assets/images/809Melmetal.png' }
];

class PokeDomManager {
  constructor(pokedata) {
    this.view = document.createDocumentFragment();
    this.answerInput = document.getElementById('answer');
    this.mic = document.getElementById('mic');

    this.pokes = {};
    this.pokeMap = new Map();
    this.pokeMapKeys;
    this.answered = [];
    this.listener = {
      speech: e => this.speech(e),
      speechResult: e => this.speechResult(e)
    };

    pokedata.forEach(d => {
      d.keyword.forEach(k => this.pokeMap.set(k, `id${d.id}`));

      const poke = new Poke(d);
      this.pokes[`id${d.id}`] = poke;

      this.view.appendChild(poke.view);
    });
    this.pokeMapKeys = [...this.pokeMap.keys()];

    const p = document.createDocumentFragment();
    const progress = document.createElement('span');
    const slash = document.createTextNode('/');
    const total = document.createElement('span');
    progress.id = 'progress';
    total.id = 'total';
    progress.textContent = '0';
    total.textContent = pokes.length;
    p.appendChild(progress);
    p.appendChild(slash);
    p.appendChild(total);
    document.getElementById('p').textContent = '';
    document.getElementById('p').appendChild(p);

    document.getElementById('pokes').appendChild(this.view);

    const initAnswered = localStorage.getItem('answered');
    if (initAnswered) {
      JSON.parse(initAnswered).forEach(a => this.answer(a));
    }

    this.mic.addEventListener('click', this.listener.speech);
    this.answerInput.addEventListener('keydown', e => (e.key === 'Enter' ? this.submit(this.answerInput.value) : false));
  }
  submit(word) {
    const key = this.pokeMap.get(word);
    if (key) this.answer(key);
  }
  answer(key) {
    if (key && !this.answered.includes(key)) {
      this.answerInput.value = '';
      this.answered.push(key);
      this.pokes[key].active();
      document.getElementById('progress').textContent = this.answered.length;

      localStorage.setItem('answered', JSON.stringify(this.answered));
    }
  }
  speech() {
    const speech = new webkitSpeechRecognition();
    speech.lang = 'ja-JP';
    speech.interimResults = true;
    speech.continuous = true;

    speech.addEventListener('result', this.listener.speechResult);
    speech.addEventListener('error', e => console.log(e));
    speech.addEventListener('soundstart', e => console.log(e));

    speech.start();
  }
  speechResult(e) {
    const result = e.results[e.resultIndex];
    const alt = result[0];

    console.log('\n');
    console.log('RESULT:');
    console.log(e);
    console.log(alt.transcript);
    console.log(result.isFinal);

    if (result.isFinal) {
      this.pokeMapKeys.forEach(k => {
        if (alt.transcript.includes(k)) {
          this.submit(k);
        }
      });
      this.answerInput.classList.remove('speech');
    } else {
      this.answerInput.value = alt.transcript;
      this.answerInput.classList.add('speech');
    }
  }
}
class Poke {
  constructor(poke) {
    this.id = poke.id;
    this.name = poke.name;
    this.image = poke.image;

    this.view = document.createElement('div');
    this.viewItem = {
      imagearea: document.createElement('div'),
      bone: document.createElement('div'),
      image: document.createElement('img'),
      primary: document.createElement('div'),
      no: document.createElement('p'),
      name: document.createElement('p')
    };

    this.view.classList.add('poke');
    this.viewItem.imagearea.classList.add('poke-imgarea');
    this.viewItem.bone.classList.add('poke-imgbone');
    this.viewItem.image.classList.add('poke-img');
    this.viewItem.primary.classList.add('poke-primary');
    this.viewItem.no.classList.add('poke-no');
    this.viewItem.name.classList.add('poke-name');

    this.viewItem.bone.textContent = '？';
    this.viewItem.no.textContent = `No: ${this.id}`;
    this.viewItem.name.textContent = '？？？？';

    this.viewItem.imagearea.appendChild(this.viewItem.bone);
    this.viewItem.primary.appendChild(this.viewItem.no);
    this.viewItem.primary.appendChild(this.viewItem.name);
    this.view.appendChild(this.viewItem.imagearea);
    this.view.appendChild(this.viewItem.primary);
  }
  active() {
    this.viewItem.image.src = this.image;
    this.viewItem.name.textContent = this.name;

    this.viewItem.imagearea.removeChild(this.viewItem.bone);
    this.viewItem.imagearea.appendChild(this.viewItem.image);

    this.view.scrollIntoView({ behavior: 'smooth', block: 'center' });
  }
}

const setting = () => {
  // setting
  localStorage.removeItem('answered');
};

const init = () => {
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker
      .register('sw.js', { scope: '/pokemon-ierukana/' })
      .then(reg => console.log('ServiceWorker registration successful with scope: ', reg.scope))
      .catch(err => console.log('ServiceWorker registration failed: ', err));
  }

  new PokeDomManager(pokes);

  document.getElementById('setting').addEventListener('click', setting);
};

init();
